{
 "title": "Cortex Flavor Usage",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "availability_zone",
    "label": "Availability Zone",
    "query": {
     "query": "label_values(cortex_flavor_running_vms, availability_zone)"
    }
   },
   {
    "name": "project_name",
    "label": "Project",
    "query": {
     "query": "label_values(cortex_flavor_running_vms, project_name)"
    }
   },
   {
    "name": "flavor_name",
    "label": "Flavor",
    "query": {
     "query": "label_values(cortex_flavor_running_vms, flavor_name)"
    }
   },
   {
    "name": "hypervisor_family",
    "label": "Hypervisor Family",
    "query": {
     "query": "label_values(cortex_flavor_running_vms, hypervisor_family)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview - Across All Selected Availability Zones",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Flavor Usage per Project - Aggregated Across All Selected AZs",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sort_desc(sum(cortex_flavor_running_vms{project_name=~\"$project_name\", flavor_name=~\"$flavor_name\", availability_zone=~\"$availability_zone\", hypervisor_family=~\"$hypervisor_family\"}) by (project_name, flavor_name, hypervisor_family))"
    }
   ]
  },
  {
   "title": "Top 20 Most Used Flavors - Across All Selected AZs",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(20,sort_desc(sum(cortex_flavor_running_vms{project_name=~\"$project_name\", flavor_name=~\"$flavor_name\", availability_zone=~\"$availability_zone\", hypervisor_family=~\"$hypervisor_family\"}) by (flavor_name)))",
     "legendFormat": "{{flavor_name}}"
    }
   ]
  },
  {
   "title": "$availability_zone",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "repeat": "availability_zone",
   "collapsed": true,
   "panels": [
    {
     "title": "Flavor Usage by Project",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sort_desc(cortex_flavor_running_vms{availability_zone=\"$availability_zone\", project_name=~\"$project_name\", flavor_name=~\"$flavor_name\", hypervisor_family=~\"$hypervisor_family\"})"
      }
     ]
    },
    {
     "title": "Top 20 Most Used Flavors - Within This AZ",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(20, sum(cortex_flavor_running_vms{availability_zone=\"$availability_zone\", flavor_name=~\"$flavor_name\", project_name=~\"$project_name\", hypervisor_family=~\"$hypervisor_family\"}) by (flavor_name))",
       "legendFormat": "{{flavor_name}} "
      }
     ]
    }
   ]
  }
 ]
}