{
 "title": "Cortex Compute VMware - Overview",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "availability_zone",
    "label": "Availability Zone",
    "query": {
     "query": "label_values(cortex_vmware_host_capacity_available, availability_zone)"
    }
   },
   {
    "name": "compute_host",
    "label": "Compute Host",
    "query": {
     "query": "label_values(cortex_vmware_host_capacity_available, compute_host)"
    }
   },
   {
    "name": "enabled",
    "label": "Enabled",
    "query": {
     "query": "label_values(cortex_vmware_host_capacity_available, enabled)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# INFO\n\nCurrently not 100% accurate. Waiting on latest cortex version to be deployed."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "README",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "This dashboard displays capacity that is available for any project to use. `General available` means the capacity is not reserved for external customers or pinned to specific projects. (For those there is a separate section=)\n\nThe displayed capacity accounts for upcoming migrations from decommissioned hosts. The capacity is calculated as following:\n\n`Available capacity on non-decommissioned hosts - Workload on decommissioned hosts / Total capacity of non-decommissioned hosts`\n\nThis is done because when a host is decommissioned, its workload must migrate to the remaining general available hosts, consuming some of their free capacity.\n\n## Example\n\nIf you have 100 cores available on non-decommissioned hosts, but 20 cores of workload are running on decommissioned hosts that need migration, the dashboard shows 80 cores as actually available.\n\n## Filters\n\n**Availability Zone**: Filter by specific availability zones or view all zones.\n\n**Compute Host**: Filter by specific hosts or view aggregated data across all hosts.\n\n**Enabled**: Set to \"true\" to only count enabled hosts (excludes hosts in maintenance). Set to \"All\" to include both enabled and disabled hosts.\n\nUse the pre-filtered sections below to view capacity by workload type and CPU architecture."
     },
     "targets": [
      {}
     ]
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "General Purpose (With commitments)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
     "legendFormat": "Raw Available CPUs"
    },
    {
     "expr": "# Unused Commitments\nsum(\n  clamp_min(\n    max by (project_id, availability_zone) (\n      limes_project_committed_per_az{\n        service=\"compute\",\n        resource=\"cores\",\n        availability_zone=~\"$availability_zone\"  # Will not be any for compute service\n      }\n    )\n    -\n    on(project_id, availability_zone)\n    max by (project_id, availability_zone) (\n      limes_project_usage_per_az{\n        service=\"compute\",\n        resource=\"cores\",\n        availability_zone=~\"$availability_zone\"\n      }\n    ),\n    0\n  )\n  or\n  max by (project_id, availability_zone) (\n      limes_project_committed_per_az{\n        service=\"compute\",\n        resource=\"cores\",\n        availability_zone=~\"$availability_zone\"  # Will not be any for compute service\n      }\n    )\n)",
     "legendFormat": "Unused Commitments"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
     "legendFormat": "Total CPUs"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      # Remove enabled from decommissioned workload, since usually decommissioned hypervisors are disabled\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
     "legendFormat": "Total Decommissioned CPUs"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
     "legendFormat": "Available Decommissioned CPUs"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
     "legendFormat": "Raw RAM "
    },
    {
     "expr": "# Unused Commitments\nsum(\n  clamp_min(\n    max by (project_id, availability_zone) (\n      limes_project_committed_per_az{\n        service=\"compute\",\n        resource=\"ram\",\n        availability_zone=~\"$availability_zone\"  # Will not be any for compute service\n      }\n    )\n    -\n    on(project_id, availability_zone)\n    max by (project_id, availability_zone) (\n      limes_project_usage_per_az{\n        service=\"compute\",\n        resource=\"ram\",\n        availability_zone=~\"$availability_zone\"\n      }\n    ),\n    0\n  )\n  or\n  max by (project_id, availability_zone) (\n      limes_project_committed_per_az{\n        service=\"compute\",\n        resource=\"ram\",\n        availability_zone=~\"$availability_zone\"  # Will not be any for compute service\n      }\n    )\n)",
     "legendFormat": "Unused RAM commitments"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
     "legendFormat": "Total RAM"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
     "legendFormat": "Total Decommissioned RAM"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
     "legendFormat": "Available Decommissioned RAM"
    },
    {
     "expr": "# No Disk commitments here\nsum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
     "legendFormat": "Raw Available Disk"
    },
    {
     "expr": "# No Disk commitments here\nsum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
     "legendFormat": "Total Disk"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
     "legendFormat": "Total Decommissioned Disk"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
     "legendFormat": "Available Decommissioned Disk"
    }
   ]
  },
  {
   "title": "HANA | Cascade Lake (No commitments)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
     "legendFormat": "Raw Available CPUs"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
     "legendFormat": "Total CPUs"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
     "legendFormat": "Total Decommissioned CPUs"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0) ",
     "legendFormat": "Available Decommissioned CPUs"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
     "legendFormat": "Raw RAM "
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
     "legendFormat": "Total RAM"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
     "legendFormat": "Total Decommissioned RAM"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0) ",
     "legendFormat": "Available Decommissioned RAM"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
     "legendFormat": "Raw Available Disk"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
     "legendFormat": "Total Disk"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
     "legendFormat": "Total Decommissioned Disk"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
     "legendFormat": "Available Decommissioned Disk"
    }
   ]
  },
  {
   "title": "HANA | Sapphire Rapids (No commitments)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
     "legendFormat": "Raw Available CPUs"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
     "legendFormat": "Total CPUs"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
     "legendFormat": "Total Decommissioned CPUs"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0) ",
     "legendFormat": "Available Decommissioned CPUs"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
     "legendFormat": "Raw RAM "
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
     "legendFormat": "Total RAM"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
     "legendFormat": "Total Decommissioned RAM"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0) ",
     "legendFormat": "Available Decommissioned RAM"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
     "legendFormat": "Raw Available Disk"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
     "legendFormat": "Total Disk"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
     "legendFormat": "Total Decommissioned Disk"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
     "legendFormat": "Available Decommissioned Disk"
    }
   ]
  },
  {
   "title": "General Purpose over time (with commitments)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit", "label": "Capacity (%)" }
   ],
   "targets": [
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
     "legendFormat": "Raw Available CPUs"
    },
    {
     "expr": "# Unused Commitments\nsum(\n  clamp_min(\n    max by (project_id, availability_zone) (\n      limes_project_committed_per_az{\n        service=\"compute\",\n        resource=\"cores\",\n        availability_zone=~\"$availability_zone\"  # Will not be any for compute service\n      }\n    )\n    -\n    on(project_id, availability_zone)\n    max by (project_id, availability_zone) (\n      limes_project_usage_per_az{\n        service=\"compute\",\n        resource=\"cores\",\n        availability_zone=~\"$availability_zone\"\n      }\n    ),\n    0\n  )\n  or\n  max by (project_id, availability_zone) (\n      limes_project_committed_per_az{\n        service=\"compute\",\n        resource=\"cores\",\n        availability_zone=~\"$availability_zone\"  # Will not be any for compute service\n      }\n    )\n)",
     "legendFormat": "Unused Commitments"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
     "legendFormat": "Total CPUs"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
     "legendFormat": "Total Decommissioned CPUs"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
     "legendFormat": "Available Decommissioned CPUs"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
     "legendFormat": "Raw RAM "
    },
    {
     "expr": "# Unused Commitments\nsum(\n  clamp_min(\n    max by (project_id, availability_zone) (\n      limes_project_committed_per_az{\n        service=\"compute\",\n        resource=\"ram\",\n        availability_zone=~\"$availability_zone\"  # Will not be any for compute service\n      }\n    )\n    -\n    on(project_id, availability_zone)\n    max by (project_id, availability_zone) (\n      limes_project_usage_per_az{\n        service=\"compute\",\n        resource=\"ram\",\n        availability_zone=~\"$availability_zone\"\n      }\n    ),\n    0\n  )\n  or\n  max by (project_id, availability_zone) (\n      limes_project_committed_per_az{\n        service=\"compute\",\n        resource=\"ram\",\n        availability_zone=~\"$availability_zone\"  # Will not be any for compute service\n      }\n    )\n)",
     "legendFormat": "Unused RAM commitments"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
     "legendFormat": "Total RAM"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
     "legendFormat": "Total Decommissioned RAM"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
     "legendFormat": "Available Decommissioned RAM"
    },
    {
     "expr": "# No Disk commitments here\nsum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
     "legendFormat": "Raw Available Disk"
    },
    {
     "expr": "# No Disk commitments here\nsum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
     "legendFormat": "Total Disk"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
     "legendFormat": "Total Decommissioned Disk"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
     "legendFormat": "Available Decommissioned Disk"
    },
    {
     "expr": "count(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_available{\n      # Use any resource here, otherwise the amount would have to be divided by 3, since the metric is exported 3 times per host (cpu, ram, disk)\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
     "legendFormat": "Active hosts"
    }
   ]
  },
  {
   "title": "HANA | Cascade Lake (No commitments)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
     "legendFormat": "Raw Available CPUs"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
     "legendFormat": "Total CPUs"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
     "legendFormat": "Total Decommissioned CPUs"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0) ",
     "legendFormat": "Available Decommissioned CPUs"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
     "legendFormat": "Raw RAM "
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
     "legendFormat": "Total RAM"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
     "legendFormat": "Total Decommissioned RAM"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0) ",
     "legendFormat": "Available Decommissioned RAM"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
     "legendFormat": "Raw Available Disk"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
     "legendFormat": "Total Disk"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
     "legendFormat": "Total Decommissioned Disk"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
     "legendFormat": "Available Decommissioned Disk"
    },
    {
     "expr": "count(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      # Use any resource here, otherwise the amount would have to be divided by 3, since the metric is exported 3 times per host (cpu, ram, disk)\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) ",
     "legendFormat": "Active hosts"
    }
   ]
  },
  {
   "title": "HANA | Sapphire Rapids (No commitments)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
     "legendFormat": "Raw Available CPUs"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
     "legendFormat": "Total CPUs"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
     "legendFormat": "Total Decommissioned CPUs"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0) ",
     "legendFormat": "Available Decommissioned CPUs"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
     "legendFormat": "Raw RAM "
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
     "legendFormat": "Total RAM"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
     "legendFormat": "Total Decommissioned RAM"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0) ",
     "legendFormat": "Available Decommissioned RAM"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
     "legendFormat": "Raw Available Disk"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
     "legendFormat": "Total Disk"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
     "legendFormat": "Total Decommissioned Disk"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
     "legendFormat": "Available Decommissioned Disk"
    },
    {
     "expr": "count(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      # Use any resource here, otherwise the amount would have to be divided by 3, since the metric is exported 3 times per host (cpu, ram, disk)\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) ",
     "legendFormat": "Active hosts"
    }
   ]
  },
  {
   "title": "General Purpose (With commitments)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Amount hosts",
     "type": "stat",
     "gridPos": { "h": 12, "w": 2, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      enabled=\"true\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or on() vector(0)",
       "legendFormat": "Available"
      },
      {
       "expr": "count(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      enabled=\"false\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or on() vector(0)",
       "legendFormat": "Disabled"
      },
      {
       "expr": "count(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or on() vector(0)",
       "legendFormat": "Decommissioned"
      },
      {
       "expr": "count(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or on() vector(0)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Available capacity over time (with commitments)",
     "type": "graph",
     "gridPos": { "h": 12, "w": 7, "x": 2, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit", "label": "Capacity (%)" }
     ],
     "targets": [
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Raw Available CPUs"
      },
      {
       "expr": "# Unused Commitments\nsum(\n  clamp_min(\n    max by (project_id, availability_zone) (\n      limes_project_committed_per_az{\n        service=\"compute\",\n        resource=\"cores\",\n        availability_zone=~\"$availability_zone\"  # Will not be any for compute service\n      }\n    )\n    -\n    on(project_id, availability_zone)\n    max by (project_id, availability_zone) (\n      limes_project_usage_per_az{\n        service=\"compute\",\n        resource=\"cores\",\n        availability_zone=~\"$availability_zone\"\n      }\n    ),\n    0\n  )\n  or\n  max by (project_id, availability_zone) (\n      limes_project_committed_per_az{\n        service=\"compute\",\n        resource=\"cores\",\n        availability_zone=~\"$availability_zone\"  # Will not be any for compute service\n      }\n    )\n)",
       "legendFormat": "Unused Commitments"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total CPUs"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Total Decommissioned CPUs"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Available Decommissioned CPUs"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Raw RAM "
      },
      {
       "expr": "# Unused Commitments\nsum(\n  clamp_min(\n    max by (project_id, availability_zone) (\n      limes_project_committed_per_az{\n        service=\"compute\",\n        resource=\"ram\",\n        availability_zone=~\"$availability_zone\"  # Will not be any for compute service\n      }\n    )\n    -\n    on(project_id, availability_zone)\n    max by (project_id, availability_zone) (\n      limes_project_usage_per_az{\n        service=\"compute\",\n        resource=\"ram\",\n        availability_zone=~\"$availability_zone\"\n      }\n    ),\n    0\n  )\n  or\n  max by (project_id, availability_zone) (\n      limes_project_committed_per_az{\n        service=\"compute\",\n        resource=\"ram\",\n        availability_zone=~\"$availability_zone\"  # Will not be any for compute service\n      }\n    )\n)",
       "legendFormat": "Unused RAM commitments"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total RAM"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Total Decommissioned RAM"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Available Decommissioned RAM"
      },
      {
       "expr": "# No Disk commitments here\nsum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Raw Available Disk"
      },
      {
       "expr": "# No Disk commitments here\nsum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total Disk"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Total Decommissioned Disk"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Available Decommissioned Disk"
      },
      {
       "expr": "count(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_available{\n      # Use any resource here, otherwise the amount would have to be divided by 3, since the metric is exported 3 times per host (cpu, ram, disk)\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Active hosts"
      }
     ]
    },
    {
     "title": "CPU (With commitments)",
     "type": "stat",
     "gridPos": { "h": 12, "w": 5, "x": 9, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Raw Available CPUs"
      },
      {
       "expr": "# Unused Commitments\nsum(\n  clamp_min(\n    max by (project_id, availability_zone) (\n      limes_project_committed_per_az{\n        service=\"compute\",\n        resource=\"cores\",\n        availability_zone=~\"$availability_zone\"  # Will not be any for compute service\n      }\n    )\n    -\n    on(project_id, availability_zone)\n    max by (project_id, availability_zone) (\n      limes_project_usage_per_az{\n        service=\"compute\",\n        resource=\"cores\",\n        availability_zone=~\"$availability_zone\"\n      }\n    ),\n    0\n  )\n  or\n  max by (project_id, availability_zone) (\n      limes_project_committed_per_az{\n        service=\"compute\",\n        resource=\"cores\",\n        availability_zone=~\"$availability_zone\"  # Will not be any for compute service\n      }\n    )\n)",
       "legendFormat": "Unused Commitments"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total CPUs"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Total Decommissioned CPUs"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Available Decommissioned CPUs"
      }
     ]
    },
    {
     "title": "RAM (With commitments)",
     "type": "stat",
     "gridPos": { "h": 12, "w": 5, "x": 14, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Raw RAM "
      },
      {
       "expr": "# Unused Commitments\nsum(\n  clamp_min(\n    max by (project_id, availability_zone) (\n      limes_project_committed_per_az{\n        service=\"compute\",\n        resource=\"ram\",\n        availability_zone=~\"$availability_zone\"  # Will not be any for compute service\n      }\n    )\n    -\n    on(project_id, availability_zone)\n    max by (project_id, availability_zone) (\n      limes_project_usage_per_az{\n        service=\"compute\",\n        resource=\"ram\",\n        availability_zone=~\"$availability_zone\"\n      }\n    ),\n    0\n  )\n  or\n  max by (project_id, availability_zone) (\n      limes_project_committed_per_az{\n        service=\"compute\",\n        resource=\"ram\",\n        availability_zone=~\"$availability_zone\"  # Will not be any for compute service\n      }\n    )\n)",
       "legendFormat": "Unused RAM commitments"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total RAM"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Total Decommissioned RAM"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Available Decommissioned RAM"
      }
     ]
    },
    {
     "title": "DIsk (No commitments)",
     "type": "stat",
     "gridPos": { "h": 12, "w": 5, "x": 19, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "# No Disk commitments here\nsum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Raw Available Disk"
      },
      {
       "expr": "# No Disk commitments here\nsum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total Disk"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Total Decommissioned Disk"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Available Decommissioned Disk"
      }
     ]
    }
   ]
  },
  {
   "title": "General Purpose | Cascade Lake (No commitments)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hosts",
     "type": "stat",
     "gridPos": { "h": 12, "w": 2, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"cascade-lake\",\n      enabled=\"true\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or on() vector(0)",
       "legendFormat": "Available"
      },
      {
       "expr": "count(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"cascade-lake\",\n      enabled=\"false\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or on() vector(0)",
       "legendFormat": "Disabled"
      },
      {
       "expr": "count(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"cascade-lake\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or on() vector(0)",
       "legendFormat": "Decommissioned"
      },
      {
       "expr": "count(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"cascade-lake\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or on() vector(0)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Available capacity over time (No commitments)",
     "type": "graph",
     "gridPos": { "h": 12, "w": 7, "x": 2, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"cascade-lake\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Raw Available CPUs"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"cascade-lake\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total CPUs"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"cascade-lake\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Total Decommissioned CPUs"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"cascade-lake\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0) ",
       "legendFormat": "Available Decommissioned CPUs"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"cascade-lake\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Raw RAM "
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"cascade-lake\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total RAM"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"cascade-lake\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Total Decommissioned RAM"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"cascade-lake\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0) ",
       "legendFormat": "Available Decommissioned RAM"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"cascade-lake\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Raw Available Disk"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"cascade-lake\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total Disk"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"cascade-lake\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Total Decommissioned Disk"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"cascade-lake\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Available Decommissioned Disk"
      },
      {
       "expr": "count(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      # Use any resource here, otherwise the amount would have to be divided by 3, since the metric is exported 3 times per host (cpu, ram, disk)\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"cascade-lake\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) ",
       "legendFormat": "Active hosts"
      }
     ]
    },
    {
     "title": "CPU (No commitments)",
     "type": "stat",
     "gridPos": { "h": 12, "w": 5, "x": 9, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"cascade-lake\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Raw Available CPUs"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"cascade-lake\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total CPUs"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"cascade-lake\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Total Decommissioned CPUs"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"cascade-lake\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0) ",
       "legendFormat": "Available Decommissioned CPUs"
      }
     ]
    },
    {
     "title": "RAM (No commitments)",
     "type": "stat",
     "gridPos": { "h": 12, "w": 5, "x": 14, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"cascade-lake\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Raw RAM "
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"cascade-lake\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total RAM"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"cascade-lake\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Total Decommissioned RAM"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"cascade-lake\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0) ",
       "legendFormat": "Available Decommissioned RAM"
      }
     ]
    },
    {
     "title": "Disk (No commitments)",
     "type": "stat",
     "gridPos": { "h": 12, "w": 5, "x": 19, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"cascade-lake\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Raw Available Disk"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"cascade-lake\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total Disk"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"cascade-lake\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Total Decommissioned Disk"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"cascade-lake\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Available Decommissioned Disk"
      }
     ]
    }
   ]
  },
  {
   "title": "General Purpose | Sapphire Rapids (No commitments)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hosts",
     "type": "stat",
     "gridPos": { "h": 12, "w": 2, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"sapphire-rapids\",\n      enabled=\"true\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or on() vector(0)",
       "legendFormat": "Available"
      },
      {
       "expr": "count(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"sapphire-rapids\",\n      enabled=\"false\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or on() vector(0)",
       "legendFormat": "Disabled"
      },
      {
       "expr": "count(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"sapphire-rapids\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or on() vector(0)",
       "legendFormat": "Decommissioned"
      },
      {
       "expr": "count(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"sapphire-rapids\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or on() vector(0)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Available capacity over time (No commitments)",
     "type": "graph",
     "gridPos": { "h": 12, "w": 7, "x": 2, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"sapphire-rapids\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Raw Available CPUs"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"sapphire-rapids\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total CPUs"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"sapphire-rapids\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Total Decommissioned CPUs"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"sapphire-rapids\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0) ",
       "legendFormat": "Available Decommissioned CPUs"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"sapphire-rapids\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Raw RAM "
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"sapphire-rapids\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total RAM"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"sapphire-rapids\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Total Decommissioned RAM"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"sapphire-rapids\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0) ",
       "legendFormat": "Available Decommissioned RAM"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"sapphire-rapids\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Raw Available Disk"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"sapphire-rapids\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total Disk"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"sapphire-rapids\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Total Decommissioned Disk"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"sapphire-rapids\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Available Decommissioned Disk"
      },
      {
       "expr": "count(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      # Use any resource here, otherwise the amount would have to be divided by 3, since the metric is exported 3 times per host (cpu, ram, disk)\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"sapphire-rapids\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) ",
       "legendFormat": "Active hosts"
      }
     ]
    },
    {
     "title": "CPU (No commitments)",
     "type": "stat",
     "gridPos": { "h": 12, "w": 5, "x": 9, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"sapphire-rapids\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Raw Available CPUs"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"sapphire-rapids\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total CPUs"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"sapphire-rapids\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Total Decommissioned CPUs"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"sapphire-rapids\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0) ",
       "legendFormat": "Available Decommissioned CPUs"
      }
     ]
    },
    {
     "title": "RAM (No commitments)",
     "type": "stat",
     "gridPos": { "h": 12, "w": 5, "x": 14, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"sapphire-rapids\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Raw RAM "
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"sapphire-rapids\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total RAM"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"sapphire-rapids\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Total Decommissioned RAM"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"sapphire-rapids\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0) ",
       "legendFormat": "Available Decommissioned RAM"
      }
     ]
    },
    {
     "title": "Disk (No commitments)",
     "type": "stat",
     "gridPos": { "h": 12, "w": 5, "x": 19, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"sapphire-rapids\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Raw Available Disk"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"sapphire-rapids\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total Disk"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"sapphire-rapids\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Total Decommissioned Disk"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"sapphire-rapids\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Available Decommissioned Disk"
      }
     ]
    }
   ]
  },
  {
   "title": "HANA | Cascade Lake (No commitments)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hosts",
     "type": "stat",
     "gridPos": { "h": 12, "w": 2, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      enabled=\"true\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or on() vector(0)",
       "legendFormat": "Available"
      },
      {
       "expr": "count(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      enabled=\"false\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or on() vector(0)",
       "legendFormat": "Disabled"
      },
      {
       "expr": "count(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or on() vector(0)",
       "legendFormat": "Decommissioned"
      },
      {
       "expr": "count(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or on() vector(0)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Available capacity over time (No commitments)",
     "type": "graph",
     "gridPos": { "h": 12, "w": 7, "x": 2, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Raw Available CPUs"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total CPUs"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Total Decommissioned CPUs"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0) ",
       "legendFormat": "Available Decommissioned CPUs"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Raw RAM "
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total RAM"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Total Decommissioned RAM"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0) ",
       "legendFormat": "Available Decommissioned RAM"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Raw Available Disk"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total Disk"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Total Decommissioned Disk"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Available Decommissioned Disk"
      },
      {
       "expr": "count(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      # Use any resource here, otherwise the amount would have to be divided by 3, since the metric is exported 3 times per host (cpu, ram, disk)\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) ",
       "legendFormat": "Active hosts"
      }
     ]
    },
    {
     "title": "CPU (No commitments)",
     "type": "stat",
     "gridPos": { "h": 12, "w": 5, "x": 9, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Raw Available CPUs"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total CPUs"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Total Decommissioned CPUs"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0) ",
       "legendFormat": "Available Decommissioned CPUs"
      }
     ]
    },
    {
     "title": "RAM (No commitments)",
     "type": "stat",
     "gridPos": { "h": 12, "w": 5, "x": 14, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Raw RAM "
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total RAM"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Total Decommissioned RAM"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0) ",
       "legendFormat": "Available Decommissioned RAM"
      }
     ]
    },
    {
     "title": "Disk (No commitments)",
     "type": "stat",
     "gridPos": { "h": 12, "w": 5, "x": 19, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Raw Available Disk"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total Disk"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Total Decommissioned Disk"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Available Decommissioned Disk"
      }
     ]
    }
   ]
  },
  {
   "title": "HANA | Sapphire Rapids (No commitments)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hosts",
     "type": "stat",
     "gridPos": { "h": 12, "w": 2, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      enabled=\"true\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or on() vector(0)",
       "legendFormat": "Available"
      },
      {
       "expr": "count(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      enabled=\"false\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or on() vector(0)",
       "legendFormat": "Disabled"
      },
      {
       "expr": "count(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or on() vector(0)",
       "legendFormat": "Decommissioned"
      },
      {
       "expr": "count(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or on() vector(0)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Available capacity over time (No commitments)",
     "type": "graph",
     "gridPos": { "h": 12, "w": 7, "x": 2, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Raw Available CPUs"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total CPUs"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Total Decommissioned CPUs"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0) ",
       "legendFormat": "Available Decommissioned CPUs"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Raw RAM "
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total RAM"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Total Decommissioned RAM"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0) ",
       "legendFormat": "Available Decommissioned RAM"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Raw Available Disk"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total Disk"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Total Decommissioned Disk"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Available Decommissioned Disk"
      },
      {
       "expr": "count(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      # Use any resource here, otherwise the amount would have to be divided by 3, since the metric is exported 3 times per host (cpu, ram, disk)\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) ",
       "legendFormat": "Active hosts"
      }
     ]
    },
    {
     "title": "CPU (No commitments)",
     "type": "stat",
     "gridPos": { "h": 12, "w": 5, "x": 9, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Raw Available CPUs"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total CPUs"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Total Decommissioned CPUs"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0) ",
       "legendFormat": "Available Decommissioned CPUs"
      }
     ]
    },
    {
     "title": "RAM (No commitments)",
     "type": "stat",
     "gridPos": { "h": 12, "w": 5, "x": 14, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Raw RAM "
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total RAM"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Total Decommissioned RAM"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0) ",
       "legendFormat": "Available Decommissioned RAM"
      }
     ]
    },
    {
     "title": "Disk (No commitments)",
     "type": "stat",
     "gridPos": { "h": 12, "w": 5, "x": 19, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Raw Available Disk"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      enabled=~\"$enabled\",\n      decommissioned=\"false\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total Disk"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Total Decommissioned Disk"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      decommissioned=\"true\",\n      external_customer=\"false\",\n      pinned_project!=\"true\"\n    }\n  )\n) or vector(0)",
       "legendFormat": "Available Decommissioned Disk"
      }
     ]
    }
   ]
  },
  {
   "title": "External Customer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true
  },
  {
   "title": "Capacity pinned to projects",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true
  }
 ]
}