{
 "title": "Cortex VMware Compute Infrastructure - Details",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "availability_zone",
    "label": "Availability Zone",
    "query": {
     "query": "label_values(cortex_vmware_host_capacity_available, availability_zone)"
    }
   },
   {
    "name": "compute_host",
    "label": "Compute Host",
    "query": {
     "query": "label_values(cortex_vmware_host_capacity_available, compute_host)"
    }
   },
   {
    "name": "workload_type",
    "label": "Workload Type",
    "query": {
     "query": "label_values(cortex_vmware_host_capacity_available, workload_type)"
    }
   },
   {
    "name": "cpu_architecture",
    "label": "CPU Architecture",
    "query": {
     "query": "label_values(cortex_vmware_host_capacity_available, cpu_architecture)"
    }
   },
   {
    "name": "enabled",
    "label": "Enabled",
    "query": {
     "query": "label_values(cortex_vmware_host_capacity_available, enabled)"
    }
   },
   {
    "name": "decommissioned",
    "label": "Decommissioned",
    "query": {
     "query": "label_values(cortex_vmware_host_capacity_available, decommissioned)"
    }
   },
   {
    "name": "external_customer",
    "label": "External Customer",
    "query": {
     "query": "label_values(cortex_vmware_host_capacity_available, external_customer)"
    }
   },
   {
    "name": "pinned_projects",
    "label": "Pinned Projects",
    "query": {
     "query": "label_values(cortex_vmware_host_capacity_available, pinned_projects)"
    }
   },
   { "name": "Project ID" }
  ]
 },
 "panels": [
  {
   "title": "vCPU Capacity",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=~\"$workload_type\",\n      cpu_architecture=~\"$cpu_architecture\",\n      pinned_project_ids=~\"(^$|.*$project_id.*)\",\n      enabled=~\"$enabled\",\n      decommissioned=~\"$decommissioned\",\n      external_customer=~\"$external_customer\",\n      pinned_projects=~\"$pinned_projects\"\n    }\n  )\n)\n",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=~\"$workload_type\",\n      cpu_architecture=~\"$cpu_architecture\",\n      pinned_project_ids=~\"(^$|.*$project_id.*)\",\n      enabled=~\"$enabled\",\n      decommissioned=~\"$decommissioned\",\n      external_customer=~\"$external_customer\",\n      pinned_projects=~\"$pinned_projects\"\n    }\n  )\n)",
     "legendFormat": "Total"
    },
    {
     "expr": "predict_linear(\n  sum(\n    max by (compute_host) (\n      cortex_vmware_host_capacity_available{\n        resource=\"cpu\",\n        availability_zone=~\"$availability_zone\",\n        compute_host=~\"$compute_host\",\n        workload_type=~\"$workload_type\",\n        cpu_architecture=~\"$cpu_architecture\",\n        pinned_project_ids=~\"(^$|.*$project_id.*)\",\n        enabled=~\"$enabled\",\n        decommissioned=~\"$decommissioned\",\n        external_customer=~\"$external_customer\",\n        pinned_projects=~\"$pinned_projects\"\n      }\n    )\n  )\n[56d:4h], 4838400)",
     "legendFormat": "Predicted Capacity"
    }
   ]
  },
  {
   "title": "RAM Capacity",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=~\"$workload_type\",\n      cpu_architecture=~\"$cpu_architecture\",\n      pinned_project_ids=~\"(^$|.*$project_id.*)\",\n      enabled=~\"$enabled\",\n      decommissioned=~\"$decommissioned\",\n      external_customer=~\"$external_customer\",\n      pinned_projects=~\"$pinned_projects\"\n    }\n  )\n)\n",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=~\"$workload_type\",\n      cpu_architecture=~\"$cpu_architecture\",\n      pinned_project_ids=~\"(^$|.*$project_id.*)\",\n      enabled=~\"$enabled\",\n      decommissioned=~\"$decommissioned\",\n      external_customer=~\"$external_customer\",\n      pinned_projects=~\"$pinned_projects\"\n    }\n  )\n)",
     "legendFormat": "Total"
    },
    {
     "expr": "predict_linear(\n  sum(\n    max by (compute_host) (\n      cortex_vmware_host_capacity_available{\n        resource=\"ram\",\n        availability_zone=~\"$availability_zone\",\n        compute_host=~\"$compute_host\",\n        workload_type=~\"$workload_type\",\n        cpu_architecture=~\"$cpu_architecture\",\n        pinned_project_ids=~\"(^$|.*$project_id.*)\",\n        enabled=~\"$enabled\",\n        decommissioned=~\"$decommissioned\",\n        external_customer=~\"$external_customer\",\n        pinned_projects=~\"$pinned_projects\"\n      }\n    )\n  )\n[56d:4h], 4838400)",
     "legendFormat": "Predicted Capacity"
    }
   ]
  },
  {
   "title": "Disk Capacity",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=~\"$workload_type\",\n      cpu_architecture=~\"$cpu_architecture\",\n      pinned_project_ids=~\"(^$|.*$project_id.*)\",\n      enabled=~\"$enabled\",\n      decommissioned=~\"$decommissioned\",\n      external_customer=~\"$external_customer\",\n      pinned_projects=~\"$pinned_projects\"\n    }\n  )\n)\n",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=~\"$workload_type\",\n      cpu_architecture=~\"$cpu_architecture\",\n      pinned_project_ids=~\"(^$|.*$project_id.*)\",\n      enabled=~\"$enabled\",\n      decommissioned=~\"$decommissioned\",\n      external_customer=~\"$external_customer\",\n      pinned_projects=~\"$pinned_projects\"\n    }\n  )\n)",
     "legendFormat": "Total"
    },
    {
     "expr": "predict_linear(\n  sum(\n    max by (compute_host) (\n      cortex_vmware_host_capacity_available{\n        resource=\"disk\",\n        availability_zone=~\"$availability_zone\",\n        compute_host=~\"$compute_host\",\n        workload_type=~\"$workload_type\",\n        cpu_architecture=~\"$cpu_architecture\",\n        pinned_project_ids=~\"(^$|.*$project_id.*)\",\n        enabled=~\"$enabled\",\n        decommissioned=~\"$decommissioned\",\n        external_customer=~\"$external_customer\",\n        pinned_projects=~\"$pinned_projects\"\n      }\n    )\n  )\n[56d:4h], 4838400)",
     "legendFormat": "Predicted Capacity"
    }
   ]
  },
  {
   "title": "vCPUs over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=~\"$workload_type\",\n      cpu_architecture=~\"$cpu_architecture\",\n      pinned_project_ids=~\"(^$|.*$project_id.*)\",\n      enabled=~\"$enabled\",\n      decommissioned=~\"$decommissioned\",\n      external_customer=~\"$external_customer\",\n      pinned_projects=~\"$pinned_projects\"\n    }\n  )\n)",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=~\"$workload_type\",\n      cpu_architecture=~\"$cpu_architecture\",\n      pinned_project_ids=~\"(^$|.*$project_id.*)\",\n      enabled=~\"$enabled\",\n      decommissioned=~\"$decommissioned\",\n      external_customer=~\"$external_customer\",\n      pinned_projects=~\"$pinned_projects\"\n    }\n  )\n)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "RAM over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=~\"$workload_type\",\n      cpu_architecture=~\"$cpu_architecture\",\n      pinned_project_ids=~\"(^$|.*$project_id.*)\",\n      enabled=~\"$enabled\",\n      decommissioned=~\"$decommissioned\",\n      external_customer=~\"$external_customer\",\n      pinned_projects=~\"$pinned_projects\"\n    }\n  )\n)",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=~\"$workload_type\",\n      cpu_architecture=~\"$cpu_architecture\",\n      pinned_project_ids=~\"(^$|.*$project_id.*)\",\n      enabled=~\"$enabled\",\n      decommissioned=~\"$decommissioned\",\n      external_customer=~\"$external_customer\",\n      pinned_projects=~\"$pinned_projects\"\n    }\n  )\n)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Disk over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=~\"$workload_type\",\n      cpu_architecture=~\"$cpu_architecture\",\n      pinned_project_ids=~\"(^$|.*$project_id.*)\",\n      enabled=~\"$enabled\",\n      decommissioned=~\"$decommissioned\",\n      external_customer=~\"$external_customer\",\n      pinned_projects=~\"$pinned_projects\"\n    }\n  )\n)",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      workload_type=~\"$workload_type\",\n      cpu_architecture=~\"$cpu_architecture\",\n      pinned_project_ids=~\"(^$|.*$project_id.*)\",\n      enabled=~\"$enabled\",\n      decommissioned=~\"$decommissioned\",\n      external_customer=~\"$external_customer\",\n      pinned_projects=~\"$pinned_projects\"\n    }\n  )\n)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Available vCPU Capacity per Host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (compute_host, enabled) (\n  cortex_vmware_host_capacity_available{\n    resource=\"cpu\",\n    availability_zone=~\"$availability_zone\",\n    compute_host=~\"$compute_host\",\n    workload_type=~\"$workload_type\",\n    cpu_architecture=~\"$cpu_architecture\",\n    pinned_project_ids=~\"(^$|.*$project_id.*)\",\n    enabled=~\"$enabled\",\n    decommissioned=~\"$decommissioned\",\n    external_customer=~\"$external_customer\",\n    pinned_projects=~\"$pinned_projects\"\n  }\n)\n",
     "legendFormat": "{{compute_host}} (Enabled: {{enabled}})"
    }
   ]
  },
  {
   "title": "Available RAM Capacity per Host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "max by (compute_host, enabled) (\n  cortex_vmware_host_capacity_available{\n    resource=\"ram\",\n    availability_zone=~\"$availability_zone\",\n    compute_host=~\"$compute_host\",\n    workload_type=~\"$workload_type\",\n    cpu_architecture=~\"$cpu_architecture\",\n    pinned_project_ids=~\"(^$|.*$project_id.*)\",\n    enabled=~\"$enabled\",\n    decommissioned=~\"$decommissioned\",\n    external_customer=~\"$external_customer\",\n    pinned_projects=~\"$pinned_projects\"\n  }\n) \n",
     "legendFormat": "{{compute_host}} {{enabled}}"
    }
   ]
  },
  {
   "title": "Available Disk Capacity per Host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "expr": "max by (compute_host, enabled) (\n  cortex_vmware_host_capacity_available{\n    resource=\"disk\",\n    availability_zone=~\"$availability_zone\",\n    compute_host=~\"$compute_host\",\n    workload_type=~\"$workload_type\",\n    cpu_architecture=~\"$cpu_architecture\",\n    pinned_project_ids=~\"(^$|.*$project_id.*)\",\n    enabled=~\"$enabled\",\n    decommissioned=~\"$decommissioned\",\n    external_customer=~\"$external_customer\",\n    pinned_projects=~\"$pinned_projects\"\n  }\n) \n",
     "legendFormat": "{{compute_host}} {{enabled}}"
    }
   ]
  },
  {
   "title": "Hosts",
   "type": "table",
   "gridPos": { "h": 28, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "# Add all column names here\nmax by (compute_host, disabled_reason, workload_type, availability_zone, cpu_architecture, pinned_project_ids, enabled, external_customer, pinned_projects, decommissioned) (cortex_vmware_host_capacity_available{resource=\"cpu\", availability_zone=~\"$availability_zone\", compute_host=~\"$compute_host\", workload_type=~\"$workload_type\", cpu_architecture=~\"$cpu_architecture\", pinned_project_ids=~\"(^$|.*$project_id.*)\", enabled=~\"$enabled\", decommissioned=~\"$decommissioned\", external_customer=~\"$external_customer\", pinned_projects=~\"$pinned_projects\"})"
    },
    {
     "expr": "max by (compute_host) (cortex_vmware_host_capacity_available{resource=\"ram\", availability_zone=~\"$availability_zone\", compute_host=~\"$compute_host\", workload_type=~\"$workload_type\", cpu_architecture=~\"$cpu_architecture\", pinned_project_ids=~\"(^$|.*$project_id.*)\", enabled=~\"$enabled\", decommissioned=~\"$decommissioned\", external_customer=~\"$external_customer\", pinned_projects=~\"$pinned_projects\"})"
    },
    {
     "expr": "max by (compute_host) (cortex_vmware_host_capacity_available{resource=\"disk\", availability_zone=~\"$availability_zone\", compute_host=~\"$compute_host\", workload_type=~\"$workload_type\", cpu_architecture=~\"$cpu_architecture\", pinned_project_ids=~\"(^$|.*$project_id.*)\", enabled=~\"$enabled\", decommissioned=~\"$decommissioned\", external_customer=~\"$external_customer\", pinned_projects=~\"$pinned_projects\"})"
    },
    {
     "expr": "max by (compute_host) (cortex_vmware_host_capacity_total{resource=\"cpu\", availability_zone=~\"$availability_zone\", compute_host=~\"$compute_host\", workload_type=~\"$workload_type\", cpu_architecture=~\"$cpu_architecture\", pinned_project_ids=~\"(^$|.*$project_id.*)\", enabled=~\"$enabled\", decommissioned=~\"$decommissioned\", external_customer=~\"$external_customer\", pinned_projects=~\"$pinned_projects\"})"
    },
    {
     "expr": "max by (compute_host) (cortex_vmware_host_capacity_total{resource=\"ram\", availability_zone=~\"$availability_zone\", compute_host=~\"$compute_host\", workload_type=~\"$workload_type\", cpu_architecture=~\"$cpu_architecture\", pinned_project_ids=~\"(^$|.*$project_id.*)\", enabled=~\"$enabled\", decommissioned=~\"$decommissioned\", external_customer=~\"$external_customer\", pinned_projects=~\"$pinned_projects\"})"
    },
    {
     "expr": "max by (compute_host) (cortex_vmware_host_capacity_total{resource=\"disk\", availability_zone=~\"$availability_zone\", compute_host=~\"$compute_host\", workload_type=~\"$workload_type\", cpu_architecture=~\"$cpu_architecture\", pinned_project_ids=~\"(^$|.*$project_id.*)\", enabled=~\"$enabled\", decommissioned=~\"$decommissioned\", external_customer=~\"$external_customer\", pinned_projects=~\"$pinned_projects\"})"
    },
    {
     "expr": "max by (compute_host) (cortex_sap_running_vms_per_host{availability_zone=~\"$availability_zone\", compute_host=~\"$compute_host\", workload_type=~\"$workload_type\", cpu_architecture=~\"$cpu_architecture\", pinned_project_ids=~\"(^$|.*$project_id.*)\", enabled=~\"$enabled\", decommissioned=~\"$decommissioned\", external_customer=~\"$external_customer\", pinned_projects=~\"$pinned_projects\"}) "
    }
   ]
  },
  {
   "title": "Available vCPU Capacity over Time (%)",
   "type": "heatmap",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "max by (compute_host) (\n  cortex_vmware_host_capacity_available{\n    resource=\"cpu\",\n    availability_zone=~\"$availability_zone\",\n    compute_host=~\"$compute_host\",\n        workload_type=~\"$workload_type\",\n    cpu_architecture=~\"$cpu_architecture\",\n    pinned_project_ids=~\"(^$|.*$project_id.*)\",\n    enabled=~\"$enabled\"\n  }\n) \n/\nmax by (compute_host) (\n  cortex_vmware_host_capacity_total{\n    resource=\"cpu\",\n    availability_zone=~\"$availability_zone\",\n    compute_host=~\"$compute_host\",\n        workload_type=~\"$workload_type\",\n    cpu_architecture=~\"$cpu_architecture\",\n    pinned_project_ids=~\"(^$|.*$project_id.*)\",\n    enabled=~\"$enabled\"\n  }\n) * 100",
     "legendFormat": "{{compute_host}}"
    }
   ]
  },
  {
   "title": "Available RAM Capacity over Time (%)",
   "type": "heatmap",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "max by (compute_host) (\n  cortex_vmware_host_capacity_available{\n    resource=\"ram\",\n    availability_zone=~\"$availability_zone\",\n    compute_host=~\"$compute_host\",\n        workload_type=~\"$workload_type\",\n    cpu_architecture=~\"$cpu_architecture\",\n    pinned_project_ids=~\"(^$|.*$project_id.*)\",\n    enabled=~\"$enabled\"\n  }\n) \n/\nmax by (compute_host) (\n  cortex_vmware_host_capacity_total{\n    resource=\"ram\",\n    availability_zone=~\"$availability_zone\",\n    compute_host=~\"$compute_host\",\n        workload_type=~\"$workload_type\",\n    cpu_architecture=~\"$cpu_architecture\",\n    pinned_project_ids=~\"(^$|.*$project_id.*)\",\n    enabled=~\"$enabled\"\n  }\n) * 100",
     "legendFormat": "{{compute_host}}"
    }
   ]
  },
  {
   "title": "Available Disk Capacity over Time (%)",
   "type": "heatmap",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "max by (compute_host) (\n  cortex_vmware_host_capacity_available{\n    resource=\"disk\",\n    availability_zone=~\"$availability_zone\",\n    compute_host=~\"$compute_host\",\n        workload_type=~\"$workload_type\",\n    cpu_architecture=~\"$cpu_architecture\",\n    pinned_project_ids=~\"(^$|.*$project_id.*)\",\n    enabled=~\"$enabled\"\n  }\n) \n/\nmax by (compute_host) (\n  cortex_vmware_host_capacity_total{\n    resource=\"disk\",\n    availability_zone=~\"$availability_zone\",\n    compute_host=~\"$compute_host\",\n        workload_type=~\"$workload_type\",\n    cpu_architecture=~\"$cpu_architecture\",\n    pinned_project_ids=~\"(^$|.*$project_id.*)\",\n    enabled=~\"$enabled\"\n  }\n) * 100",
     "legendFormat": "{{compute_host}}"
    }
   ]
  }
 ]
}