{{- if .Values.rbac.enable }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- if and .Values.deployment.serviceAccount .Values.deployment.serviceAccount.annotations }}
  annotations:
    {{- range $key, $value := .Values.deployment.serviceAccount.annotations }}
    {{ $key }}: {{ $value }}
    {{- end }}
  {{- end }}
  name: {{ .Values.namePrefix }}-{{ .Values.deployment.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
