apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.namePrefix }}-shim-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8080
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
{{- if .Values.metrics.enable }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.namePrefix }}-shim-metrics-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  ports:
    - port: 2112
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
{{- end }}
