# Copyright 2025 SAP SE
# SPDX-License-Identifier: Apache-2.0

# These will always be mounted into the postgres container since the mount
# is done unconditionally through the helm values of the bitnami postgresql chart.
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.postgresql.fullnameOverride }}-pre-upgrade-script
data:
  pre-upgrade.sh: |
  {{- range .Files.Lines "files/pre-upgrade.sh" }}
    {{ . }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.postgresql.fullnameOverride }}-post-upgrade-script
data:
  post-upgrade.sh: |
  {{- range .Files.Lines "files/post-upgrade.sh" }}
    {{ . }}
  {{- end }}