kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "cortex-postgres.versionedFullname" . }}-max-conns
  labels:
    {{- include "cortex-postgres.labels" . | nindent 4 }}
data:
  max_conns.sql: "ALTER SYSTEM SET max_connections = 256;"
