# Copyright 2025 SAP SE
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.upgradeJob.enabled }}
# ServiceAccount used by the upgrade job to manage the Postgres StatefulSet
# and execute commands in the Postgres pod.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.postgresql.fullnameOverride }}-job-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.postgresql.fullnameOverride }}-job-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "patch", "update"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "update"]
  - apiGroups: ["apps"]
    resources: ["statefulsets/scale"]
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.postgresql.fullnameOverride }}-job-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.postgresql.fullnameOverride }}-job-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.postgresql.fullnameOverride }}-job-sa
{{- end }}
