apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  schedulerName: pods
  tolerations:
  - key: "kwok.x-k8s.io/node"
    operator: "Exists"
    effect: "NoSchedule"
  containers:
    - name: nginx
      image: nginx:latest
