apiVersion: v2
description: Prometheus alerts setup for Cortex.
name: cortex-alerts
version: 0.0.2
dependencies:
  # CRDs of the prometheus operator, such as PrometheusRule, ServiceMonitor, etc.
  - name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    version: 69.3.2
    condition: kube-prometheus-stack.enabled
  # Owner info adds a configmap to the kubernetes cluster with information on
  # the service owner. This makes it easier to find out who to contact in case
  # of issues. See: https://github.com/sapcc/helm-charts/pkgs/container/helm-charts%2Fowner-info
  - name: owner-info
    repository: oci://ghcr.io/sapcc/helm-charts
    version: 1.0.0