global:
  prometheus: cortex-prometheus

alerts:
  # Labels applied to all alerts.
  labels:
    service: cortex
  # Labels applied to specific alert levels.
  # Can be used, e.g., to push to different alerting channels.
  info:
    labels: {}
  warning:
    labels: {}
  critical:
    labels: {}
  # Labels applied to specific alerts.
  cortexDown:
    labels: {}
  cortexHttpRequest400sTooHigh:
    labels: {}
  cortexHttpRequest500sTooHigh:
    labels: {}
  cortexHighMemoryUsage:
    labels: {}
  cortexHighCPUUsage:
    labels: {}
  cortexLongPipelineRun:
    labels: {}
  cortexSyncNotSuccessful:
    labels: {}
  cortexSyncObjectsDroppedToZero:
    labels: {}

kube-prometheus-stack:
  # Whether the CRDs of the prometheus-operator should be deployed
  # together with a prometheus and alertmanager instance.
  enabled: false

  # kube-prometheus-stack deploys a bunch of junk we don't need.
  # Therefore, we disable all components and only enable the prometheus operator.
  # See: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/ci/01-provision-crds-values.yaml
  coreDns:
    enabled: false
  kubeApiServer:
    enabled: false
  kubeControllerManager:
    enabled: false
  kubeDns:
    enabled: false
  kubeEtcd:
    enabled: false
  kubeProxy:
    enabled: false
  kubeScheduler:
    enabled: false
  kubeStateMetrics:
    enabled: false
  kubelet:
    enabled: false
  nodeExporter:
    enabled: false
  grafana:
    enabled: false
  defaultRules:
    create: false
  alertmanager:
    enabled: false
  prometheus:
    enabled: false
  fullnameOverride: "cortex"
  prometheusOperator:
    enabled: true
    fullnameOverride: cortex-prometheus-operator
    serviceMonitor:
      selfMonitor: false
    tls:
      enabled: false
    admissionWebhooks:
      enabled: false
    namespaces:
      releaseNamespace: true
      additional:
        - kube-system

owner-info:
  helm-chart-url: "https://github.tools.sap/cobaltcore-dev/cortex/helm/prometheus"
  maintainers:
    - "p.matthes@sap.com"
  support-group: "cobaltcore-dev"
  enabled: true