// Copyright 2025 SAP SE
// SPDX-License-Identifier: Apache-2.0

package api

import "log/slog"

// Host object from the Manila scheduler pipeline.
type ExternalSchedulerHost struct {
	// Name of the Manila share host.
	ShareHost string `json:"host"`
}

// Request generated by the Manila scheduler when calling cortex.
// The request contains a spec of the share to be scheduled, a list of hosts and
// their status, and a map of weights that were calculated by the Manila weigher
// pipeline. Some additional flags are also included.
type ExternalSchedulerRequest struct {
	// TODO: Use a more specific type for the spec.
	Spec any `json:"spec"`
	// Request context from Manila that contains additional meta information.
	Context ManilaRequestContext `json:"context"`
	// The share hosts that are available for scheduling.
	Hosts []ExternalSchedulerHost `json:"hosts"`
	// Weights map of share hosts to their weights calculated by the Manila weigher pipeline.
	Weights map[string]float64 `json:"weights"`
}

// Conform to the PipelineRequest interface.

func (r ExternalSchedulerRequest) GetSubjects() []string {
	hosts := make([]string, len(r.Hosts))
	for i, host := range r.Hosts {
		hosts[i] = host.ShareHost
	}
	return hosts
}
func (r ExternalSchedulerRequest) GetWeights() map[string]float64 {
	return r.Weights
}
func (r ExternalSchedulerRequest) GetTraceLogArgs() []slog.Attr {
	return []slog.Attr{
		slog.String("greq", r.Context.GlobalRequestID),
		slog.String("req", r.Context.RequestID),
		slog.String("user", r.Context.UserID),
		slog.String("project", r.Context.ProjectID),
	}
}

// Response generated by cortex for the Manila scheduler.
// Cortex returns an ordered list of hosts that the VM should be scheduled on.
type ExternalSchedulerResponse struct {
	Hosts []string `json:"hosts"`
}

// Manila request context object. For the spec of this object, see:
//
// - This: https://github.com/sapcc/manila/blob/4ffdfc/manila/context.py#L29
// - And: https://github.com/openstack/oslo.context/blob/db20dd/oslo_context/context.py#L329
//
// Some fields are omitted: "service_catalog", "read_deleted" (same as "show_deleted")
type ManilaRequestContext struct {
	// Fields added by oslo.context

	UserID          string   `json:"user"`
	ProjectID       string   `json:"project_id"`
	SystemScope     string   `json:"system_scope"`
	DomainID        string   `json:"domain"`
	UserDomainID    string   `json:"user_domain"`
	ProjectDomainID string   `json:"project_domain"`
	IsAdmin         bool     `json:"is_admin"`
	ReadOnly        bool     `json:"read_only"`
	ShowDeleted     bool     `json:"show_deleted"`
	AuthToken       string   `json:"auth_token"`
	RequestID       string   `json:"request_id"`
	GlobalRequestID string   `json:"global_request_id"`
	ResourceUUID    string   `json:"resource_uuid"`
	Roles           []string `json:"roles"`
	UserIdentity    string   `json:"user_identity"`
	IsAdminProject  bool     `json:"is_admin_project"`

	// Fields added by the Manila scheduler

	RemoteAddress string `json:"remote_address"`
	Timestamp     string `json:"timestamp"`
	QuotaClass    string `json:"quota_class"`
	ProjectName   string `json:"project_name"`
}
