# Copyright 2025 SAP SE
# SPDX-License-Identifier: Apache-2.0

{{ if $.Capabilities.APIVersions.Has "autoscaling.k8s.io/v1/VerticalPodAutoscaler" -}}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "cortex-mqtt.fullname" . }}-vpa
  labels:
    app: {{ include "cortex-mqtt.fullname" . }}
    {{- include "cortex-mqtt.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: "Deployment"
    name: {{ include "cortex-mqtt.fullname" . }}
  updatePolicy:
    updateMode: "Initial"
    minReplicas: 1
    maxReplicas: 1
  resourcePolicy:
    containerPolicies:
      - containerName: {{ include "cortex-mqtt.fullname" . }}
        mode: "Auto"
        minAllowed:
          cpu: "10m"
          memory: "128Mi"
        maxAllowed:
          cpu: "2"
          memory: "4Gi"
        controlledResources: ["cpu", "memory"]
        controlledValues: "RequestsAndLimits"
{{- end }}
