services:
  # Plutono is a fork of Grafana 7.5.17 under the Apache 2.0 License.
  plutono:
    image: ghcr.io/credativ/plutono:v7.5.35
    ports:
      - 3000:3000
    volumes:
      - ./plutono/provisioning:/etc/plutono/provisioning

  # Use the following command to debug this database:
  # docker-compose exec postgres psql -U postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cortex:
    build: .
    environment:
      OS_AUTH_URL: ${OS_AUTH_URL}
      OS_USERNAME: ${OS_USERNAME}
      OS_PASSWORD: ${OS_PASSWORD}
      OS_PROJECT_NAME: ${OS_PROJECT_NAME}
      OS_USER_DOMAIN_NAME: ${OS_USER_DOMAIN_NAME}
      OS_PROJECT_DOMAIN_NAME: ${OS_PROJECT_DOMAIN_NAME}
      PROMETHEUS_URL: ${PROMETHEUS_URL}

      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    restart: on-failure
    volumes:
      - .:/home/appuser

volumes:
  postgres_data: