# Copyright 2025 SAP SE
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cortex-plutono
  labels:
    app: cortex-plutono
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cortex-plutono
  template:
    metadata:
      labels:
        app: cortex-plutono
    spec:
      containers:
        - name: cortex-plutono # from local tilt build
          image: cortex-plutono
          ports:
            - containerPort: 3000