# Copyright 2025 SAP SE
# SPDX-License-Identifier: Apache-2.0

# Plutono is a fork of Grafana 7.5.17 under the Apache 2.0 License.
FROM ghcr.io/credativ/plutono:v7.5.37
COPY provisioning /etc/plutono/provisioning
COPY plutono.ini /etc/plutono/plutono.ini