# Copyright SAP SE
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cortex-visualizer
  labels:
    app: cortex-visualizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cortex-visualizer
  template:
    metadata:
      labels:
        app: cortex-visualizer
    spec:
      serviceAccountName: cortex-visualizer
      containers:
        - name: cortex-visualizer
          image: cortex-visualizer
          ports:
            - containerPort: 80
        - name: kubectl-proxy
          image: alpine:latest
          command: ["/bin/sh"]
          args:
            - -c
            - |
              apk add --no-cache curl
              curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
              chmod +x kubectl
              mv kubectl /usr/local/bin/
              kubectl proxy --port=8001 --address=0.0.0.0 --accept-hosts=.*
          ports:
            - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: cortex-visualizer
spec:
  selector:
    app: cortex-visualizer
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: kubectl-proxy
      port: 8001
      targetPort: 8001
  type: ClusterIP