# Copyright 2025 SAP SE
# SPDX-License-Identifier: Apache-2.0

FROM nginx

COPY nova.html /usr/share/nginx/html/nova.html
COPY shared.css /usr/share/nginx/html/shared.css
COPY favicon.ico /usr/share/nginx/html/favicon.ico
COPY nginx.conf /etc/nginx/conf.d/default.conf
