{
 "title": "Cortex Knowledge Extraction",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Feature Extraction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total feature extraction time",
   "type": "graph",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_feature_pipeline_step_run_duration_seconds_bucket[2m])) by (le, step))",
     "legendFormat": "{{step}}"
    }
   ]
  },
  {
   "title": "Extracted features in database",
   "type": "stat",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (step) (cortex_feature_pipeline_step_features{github_org=\"cobaltcore-dev\",github_repo=\"cortex\"}) / count by (step) (cortex_feature_pipeline_step_features{github_org=\"cobaltcore-dev\",github_repo=\"cortex\"})",
     "legendFormat": "{{datasource}}"
    }
   ]
  },
  {
   "title": "Skipped Feature Extractors (last 2 minutes)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(cortex_feature_pipeline_step_skipped{github_org=\"cobaltcore-dev\",github_repo=\"cortex\"}[2m])",
     "legendFormat": "{{step}}"
    }
   ]
  }
 ]
}