{
 "title": "Cortex Deployment",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory budget",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (go_memstats_alloc_bytes{github_org=\"cobaltcore-dev\",github_repo=\"cortex\"} / 1_000_000)",
     "legendFormat": "{{service}}"
    },
    {
     "expr": "sum by (service) (go_memstats_alloc_bytes{pod=\"cortex-postgresql-0\"} / 1_000_000)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "CPU budget",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (rate(process_cpu_seconds_total{github_org=\"cobaltcore-dev\",github_repo=\"cortex\"}[2m]))",
     "legendFormat": "{{service}}"
    },
    {
     "expr": "sum by (service) (rate(process_cpu_seconds_total{pod=\"cortex-postgresql-0\"}[2m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "Reconnection Attempts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "DB Reconnection Attempt Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (rate(cortex_db_connection_attempts_total[5m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "MQTT Reconnection Attempt Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (rate(cortex_mqtt_connection_attempts_total[5m]))",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}