{
 "title": "Cortex Commitments",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "availability_zone",
    "label": "Availability Zone",
    "query": {
     "query": "label_values(cortex_vm_commitments_total, availability_zone)"
    }
   },
   {
    "name": "status",
    "label": "Commitment Status",
    "query": {
     "query": "label_values(cortex_vm_commitments_total, status)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Compute", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Readme",
   "type": "text",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 1 },
   "options": {
    "content": "# How to read these statistics\n\nPlease note: these statistics only report the demand, not the actual capacity that will be used when the resource is allocated. \n\nFor example, a commitment may contain 1 vcpu core. If the commitment is fulfilled on a host overcommitted by a factor of 2, it will only allocate half of a physical cpu.        "
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cores committed",
   "type": "graph",
   "gridPos": { "h": 12, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (resource_name) (cortex_vm_commitments_cores_sum{availability_zone=~\"$availability_zone\",status=~\"$status\"})",
     "legendFormat": "{{ resource_name }}"
    }
   ]
  },
  {
   "title": "Memory committed",
   "type": "graph",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max by (resource_name) (cortex_vm_commitments_memory_sum{availability_zone=~\"$availability_zone\",status=~\"$status\"})",
     "legendFormat": "{{ resource_name }}"
    }
   ]
  },
  {
   "title": "Number of Commitments",
   "type": "stat",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (resource_name) (cortex_vm_commitments_total{availability_zone=~\"$availability_zone\",status=~\"$status\"})",
     "legendFormat": "{{ resource_name }}"
    }
   ]
  },
  {
   "title": "Resources Committed",
   "type": "stat",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (resource_name) (cortex_vm_commitments_sum{availability_zone=~\"$availability_zone\",status=~\"$status\"})",
     "legendFormat": "{{ resource_name }}"
    }
   ]
  }
 ]
}