{
 "title": "Cortex",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory budget",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (go_memstats_alloc_bytes{github_org=\"cobaltcore-dev\",github_repo=\"cortex\"} / 1_000_000)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "CPU budget",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (rate(process_cpu_seconds_total{github_org=\"cobaltcore-dev\",github_repo=\"cortex\"}[1m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "KPIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Life span of VMs that were deleted in the last minute",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sort(sum by (le) (increase(cortex_vm_life_span_bucket[1m])))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Residency of VMs that were migrated in the last minute",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sort(sum by (le) (increase(cortex_vm_time_until_migration_bucket[1m])))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Average life span of newly created vms by flavor",
   "type": "stat",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(sum by (flavor_name) (cortex_vm_life_span_sum) / sum by (flavor_name) (cortex_vm_life_span_count))",
     "legendFormat": "{{flavor_name}}"
    }
   ]
  },
  {
   "title": "Average time until migration by flavor",
   "type": "stat",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(sum by (flavor_name) (cortex_vm_time_until_migration_sum) / sum by (flavor_name) (cortex_vm_time_until_migration_count))",
     "legendFormat": "{{flavor_name}}"
    }
   ]
  },
  {
   "title": "Highest outgoing migration rate",
   "type": "stat",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(30, (sum by(source_host) (rate(cortex_number_of_migrations{}[1m]))))",
     "legendFormat": "{{source_host}}"
    }
   ]
  },
  {
   "title": "Number of migrations",
   "type": "stat",
   "gridPos": { "h": 11, "w": 4, "x": 10, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(type) (increase(cortex_number_of_migrations[1m]))",
     "legendFormat": "Type: {{type}}"
    }
   ]
  },
  {
   "title": "Highest incoming migration rate",
   "type": "stat",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(30, (sum by(target_host) (rate(cortex_number_of_migrations{}[1m]))))",
     "legendFormat": "{{target_host}}"
    }
   ]
  },
  { "title": "Initial Placement (Scheduler)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Resorted Hosts",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_scheduler_pipeline_step_reorderings_levenshtein_bucket[1m])) by (le, step))",
     "legendFormat": "{{step}}"
    }
   ]
  },
  {
   "title": "Requests by type",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by(vmware,rebuild,resize,live) (increase(cortex_scheduler_pipeline_requests_total{}[1m]))",
     "legendFormat": "Rebuild: {{rebuild}}, Resize: {{resize}}, Live: {{live}}, VMware: {{vmware}}"
    }
   ]
  },
  {
   "title": "Time needed to run scheduler steps",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_scheduler_pipeline_step_run_duration_seconds_bucket[1m])) by (le, step))",
     "legendFormat": "{{step}}"
    }
   ]
  },
  {
   "title": "Successful request rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cortex_scheduler_api_request_duration_seconds_count{status=~\"2.+\"}[1m])) by (method, path, status, error)",
     "legendFormat": "{{method}} {{path}} {{status}} {{error}}"
    }
   ]
  },
  {
   "title": "Error request rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cortex_scheduler_api_request_duration_seconds_count{status=~\"4.+|5.+\"}[1m])) by (method, path, status, error)",
     "legendFormat": "{{method}} {{path}} {{status}} {{error}}"
    }
   ]
  },
  {
   "title": "Average response time (success)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_scheduler_api_request_duration_seconds_bucket{status=~\"2.+\"}[1m])) by (le, method, path, status, error))",
     "legendFormat": "{{method}} {{path}} {{status}} {{error}}"
    }
   ]
  },
  {
   "title": "Average response time (error)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_scheduler_api_request_duration_seconds_bucket{status=~\"4.+|5.+\"}[1m])) by (le, method, path, status, error))",
     "legendFormat": "{{method}} {{path}} {{status}} {{error}}"
    }
   ]
  },
  {
   "title": "Most important avoiding scheduler step by host",
   "type": "stat",
   "gridPos": { "h": 31, "w": 12, "x": 0, "y": 81 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bottomk(1, min by (host, step) (rate(cortex_scheduler_pipeline_step_weight_modification[1m])) < 0) by (host)",
     "legendFormat": "{{step}} on {{host}}"
    }
   ]
  },
  {
   "title": "Most impactful upvoting scheduler step by host",
   "type": "stat",
   "gridPos": { "h": 31, "w": 12, "x": 12, "y": 81 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, max by (host, step) (rate(cortex_scheduler_pipeline_step_weight_modification[1m])) > 0) by (host)",
     "legendFormat": "{{step}} on {{host}}"
    }
   ]
  },
  { "title": "Feature Extraction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 } },
  {
   "title": "Total feature extraction time",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_feature_pipeline_step_run_duration_seconds_bucket[1m])) by (le, step))",
     "legendFormat": "{{step}}"
    }
   ]
  },
  {
   "title": "Extracted features in database",
   "type": "stat",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (step) (cortex_feature_pipeline_step_features{github_org=\"cobaltcore-dev\",github_repo=\"cortex\"}) / count by (step) (cortex_feature_pipeline_step_features{github_org=\"cobaltcore-dev\",github_repo=\"cortex\"})",
     "legendFormat": "{{datasource}}"
    }
   ]
  },
  { "title": "Data Sync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 137 } },
  {
   "title": "Total time needed to sync",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 138 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_sync_run_duration_seconds_bucket[1m])) by (le, datasource))",
     "legendFormat": "{{datasource}}"
    }
   ]
  },
  {
   "title": "Objects synced in database",
   "type": "stat",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (datasource) (cortex_sync_objects{github_org=\"cobaltcore-dev\",github_repo=\"cortex\"}) / count by (datasource) (cortex_sync_objects{github_org=\"cobaltcore-dev\",github_repo=\"cortex\"})",
     "legendFormat": "{{datasource}}"
    }
   ]
  },
  {
   "title": "Sync request success rate",
   "type": "stat",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (datasource) (cortex_sync_request_duration_seconds_count / cortex_sync_request_processed_total)) / (count by (datasource) (cortex_sync_request_duration_seconds_count / cortex_sync_request_processed_total))",
     "legendFormat": "{{datasource}}"
    }
   ]
  }
 ]
}