{
 "title": "Cortex Descheduling",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Descheduler Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Deschedulings (rate over 2min)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by(error, skipped) (rate(cortex_descheduler_pipeline_vm_descheduling_duration_seconds_count{}[2m]))",
     "legendFormat": "Error: {{error}}, Skipped: {{skipped}}"
    }
   ]
  },
  {
   "title": "Time needed to deschedule VM",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_descheduler_pipeline_vm_descheduling_duration_seconds_bucket[2m])) by (le, error, skipped))",
     "legendFormat": "Error: {{error}}, Skipped: {{skipped}}"
    }
   ]
  },
  {
   "title": "Time needed to run descheduler steps",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_descheduler_pipeline_step_run_duration_seconds_bucket[2m])) by (le, step))",
     "legendFormat": "{{step}}"
    }
   ]
  },
  {
   "title": "Triggered migrations",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (error, skipped, source_host, target_host, vm_id) (delta(cortex_descheduler_pipeline_vm_descheduling_duration_seconds_count{}[2m]))",
     "legendFormat": "{{vm_id}}: ({{source_host}}) -> ({{target_host}}), Error: {{error}}, Skipped: {{skipped}}"
    }
   ]
  }
 ]
}