{
 "title": "Cortex Reservations",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Readme",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Readme",
     "type": "text",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 9 },
     "options": {
      "content": "# Readme\n\nReservations are generated from limes commitments that are for a concrete flavor (so called instance commitments). Commitments for bare resources are not processed by cortex as there is no way to tell where and how many vms would be placed. "
     },
     "targets": [
      {}
     ]
    }
   ]
  },
  { "title": "Reservations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Disk Reserved",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "max by (host) (cortex_reservations_resources{status_phase=\"active\",resource=\"disk_gb\"})"
    }
   ]
  },
  {
   "title": "vCPUs Reserved",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "vCPUs" } },
   "targets": [
    {
     "expr": "max by (host) (cortex_reservations_resources{status_phase=\"active\",resource=\"vcpus\"})"
    }
   ]
  },
  {
   "title": "vCPUs Reserved",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "max by (host) (cortex_reservations_resources{status_phase=\"active\",resource=\"memory_mb\"})"
    }
   ]
  },
  {
   "title": "Total Resources Reserved",
   "type": "stat",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (resource) (cortex_reservations_resources{status_phase=\"active\"})",
     "legendFormat": "{{ resource }}"
    }
   ]
  },
  {
   "title": "Disk Not Reservable",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "max by (status_error) (cortex_reservations_resources{status_phase!=\"active\",resource=\"disk_gb\"})"
    }
   ]
  },
  {
   "title": "vCPUs Not Reservable",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "vCPUs" } },
   "targets": [
    {
     "expr": "max by (status_error) (cortex_reservations_resources{status_phase!=\"active\",resource=\"vcpus\"})"
    }
   ]
  },
  {
   "title": "vCPUs Not Reservable",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "max by (status_error) (cortex_reservations_resources{status_phase!=\"active\",resource=\"memory_mb\"})"
    }
   ]
  },
  {
   "title": "Total Resources Not Reservable",
   "type": "stat",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (resource) (cortex_reservations_resources{status_phase!=\"active\"})",
     "legendFormat": "{{ resource }}"
    }
   ]
  },
  { "title": "Operator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Time to reconcile",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(controller_runtime_reconcile_time_seconds_bucket{controller=\"reservation\"}[2m])) by (le))",
     "legendFormat": "Reservations controller"
    }
   ]
  }
 ]
}