apiVersion: compute.ironcore.dev/v1alpha1
kind: Machine
metadata:
  name: machine-sample
spec:
  machineClassRef:
    name: machineclass-sample
  #  machinePoolRef:
  #    name: default
  image: my-image
  ignitionRef:
    name: my-ignition-secret
  # This is a custom field added by the cortex integration.
  # Note: The machine spec currently doesn't support this field yet.
  # Thus the machine scheduler doesn't scope to this field yet.
  scheduler: ""