# Copyright 2025 SAP SE
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: cortex-mqtt
description: MQTT setup for Cortex.
type: application
version: 0.0.5
appVersion: "0.1.0"
dependencies:
  # RabbitMQ is a message broker, see: https://artifacthub.io/packages/helm/bitnami/rabbitmq
  - name: rabbitmq
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 16.0.11
