# Copyright 2025 SAP SE
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: cortex-core
description: A Helm chart deploying Cortex core services.
type: application
appVersion: "sha-f9aac5d"
version: 0.25.1
