# Copyright 2025 SAP SE
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: cortex-core
description: A Helm chart deploying Cortex core services.
type: application
version: 0.24.2
appVersion: "sha-6b2474c"
