# Copyright 2025 SAP SE
# SPDX-License-Identifier: Apache-2.0

image:
  repository: ghcr.io/cobaltcore-dev/cortex
  pullPolicy: IfNotPresent

# Can be used to override the chart name (e.g. cortex-nova).
fullnameOverride: ""
nameOverride: ""

alerts:
  enabled: true
  prometheus: openstack
  componentPrefix:

service:
  extraLabels: {} # Additional labels to add to the service.
serviceMonitor:
  extraLabels:
    # The name of the prometheus instance to use for scraping metrics.
    prometheus: openstack
  matchLabels: {} # Additional matchers to select the service for scraping metrics.

migrationsJob:
  resources:
    requests:
      memory: "512Mi"
      cpu: "100m" # Will be increased by the VPA if needed.
    limits:
      memory: "4Gi"
      cpu: "4"
  # Additional annotations for the created database migrations job.
  podAnnotations:
    # If you use linkerd, this will disable injection for the migrations job.
    # Otherwise, the linkerd-proxy container will hang around forever and
    # block the job from completing.
    "linkerd.io/inject": disabled

resources:
  requests:
    memory: "128Mi"
    cpu: "10m" # Will be increased by the VPA if needed.
  limits:
    memory: "6Gi"
    cpu: "4"

# Liveness and readiness probes for the cortex services.
livenessProbe:
  httpGet:
    path: /up
    port: api
readinessProbe:
  httpGet:
    path: /up
    port: api

# Modes in which the service should be run.
# Each mode is translated into a separate service and deployment.
modes:
  # The name of the mode will be used for the kubernetes deployments.
  # The args will be passed to the service as command line arguments, meaning
  # the passed arg need to be baked into the service binary.
  # - name:
  #   args:
  #   replicas:

# Values passed to the service through a configmap.
conf:
  logging:
    # The log level to use (debug, info, warn, error).
    level: debug
    # The log format to use (json, text).
    format: text

  # Configuration of metrics exported to the /metrics endpoint.
  monitoring:
    # The port to expose the metrics on.
    port: 2112

    # Custom labels added to the exported metrics.
    labels:
      github_org: cobaltcore-dev
      github_repo: cortex

  # MQTT broker connection parameters.
  mqtt:
    # Must match rabbitmq settings from the cortex-mqtt chart.
    url:
    # Configure how Cortex should handle lost connections to the MQTT broker.
    reconnect:
      maxRetries: 20
      retryIntervalSeconds: 1

  # The port to use for the api serve mux.
  api:
    port: 8080

  # Connection parameters for the database where data is stored.
  db:
    host:
    port: 5432
    database: postgres
    reconnect:
      maxRetries: 20
      retryIntervalSeconds: 1
      livenessPingIntervalSeconds: 5

  keystone:
    # Authentication/identity service URL for openstack.
    url:

# Values passed to the service through a kubernetes secret.
# The keys of these values should correspond to the keys used above in the conf.
#
# Note: Please only add values here that MUST be overridden using the "secrets:" key.
secrets:
  # MQTT broker connection credentials.
  mqtt:
    username: cortex
    password: secret
  # Database connection credentials.
  db:
    user: postgres
    password: secret
  keystone:
    # OpenStack login credentials also used by the OpenStack CLI.
    projectName:
    userDomainName:
    projectDomainName:
    username:
    password:
