{{- if (index .Values "cortex-shim").conf.features.enableTraits }}
{{- $cmName := (index .Values "cortex-shim").conf.traits.configMapName }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $cmName }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  traits: {{ (index .Values "cortex-shim").conf.traits.static | toJson | quote }}
{{- end }}
