groups:
- name: cortex-alerts
  rules:
  - alert: ServiceDown
    expr: up{github_org="cobaltcore-dev",github_repo="cortex"} == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Service is down"
      description: "The service is not responding."

  - alert: HttpRequest400sTooHigh
    expr: rate(cortex_scheduler_api_request_duration_seconds_count{status=~"4.+"}[5m]) > 0
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "HTTP request 400 errors too high"
      description: "The rate of HTTP request 400 errors is too high."

  - alert: HttpRequest500sTooHigh
    expr: rate(cortex_scheduler_api_request_duration_seconds_count{status=~"5.+"}[5m]) > 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "HTTP request 500 errors too high"
      description: "The rate of HTTP request 500 errors is too high."

  - alert: HighMemoryUsage
    expr: process_resident_memory_bytes{github_org="cobaltcore-dev",github_repo="cortex"} > 100 * 1024 * 1024
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High memory usage"
      description: "The service is using more than 100 MiB of memory."

  - alert: HighCPUUsage
    expr: rate(process_cpu_seconds_total{github_org="cobaltcore-dev",github_repo="cortex"}[1m]) > 0.5
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage"
      description: "The service is using more than 50% CPU."

  - alert: LongPipelineRun
    expr: histogram_quantile(0.99, rate(cortex_pipeline_run_duration_seconds_bucket[5m])) > 1
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Pipeline run duration too long"
      description: "The pipeline takes more than 1 second to run."

  - alert: SyncNotSuccessful
    expr: cortex_sync_request_processed_total - cortex_sync_request_duration_seconds_count > 0
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Sync not successful"
      description: "There are sync requests that are not successful."

  - alert: SyncObjectsDropToZero
    expr: cortex_sync_objects_total == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Sync objects dropped to zero"
      description: "The number of sync objects has dropped to zero for some resource."
