global:
  scrape_interval: '5s'
  evaluation_interval: '5s'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['cortex-alertmanager:9093']
rule_files:
  - "/etc/prometheus/alerts.yaml"

scrape_configs:
  - job_name: 'cortex'
    metrics_path: /metrics
    static_configs:
      - targets: ['cortex:2112']