---
apiVersion: v1
kind: Secret
metadata:
  name: cortex-cinder-postgres
data:
  host: {{ .Values.postgres.host | b64enc | quote }}
  user: {{ .Values.postgres.user | b64enc | quote }}
  password: {{ .Values.postgres.password | b64enc | quote }}
  database: {{ .Values.postgres.database | b64enc | quote }}
  port: {{ .Values.postgres.port | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cortex-cinder-prometheus
data:
  url: {{ .Values.datasources.prometheus.url | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cortex-cinder-openstack-keystone
data:
  url: {{ .Values.datasources.openstack.url | b64enc | quote }}
  availability: {{ .Values.datasources.openstack.availability | b64enc | quote }}
  username: {{ .Values.datasources.openstack.username | b64enc | quote }}
  password: {{ .Values.datasources.openstack.password | b64enc | quote }}
  projectName: {{ .Values.datasources.openstack.projectName | b64enc | quote }}
  userDomainName: {{ .Values.datasources.openstack.userDomainName | b64enc | quote }}
  projectDomainName: {{ .Values.datasources.openstack.projectDomainName | b64enc | quote }}
{{- if .Values.datasources.prometheus.sso.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cortex-cinder-prometheus-sso
data:
  cert: {{ .Values.datasources.prometheus.sso.cert | b64enc | quote }}
  key: {{ .Values.datasources.prometheus.sso.key | b64enc | quote }}
  selfSigned: {{ .Values.datasources.prometheus.sso.selfSigned | b64enc | quote }}
{{- end }}
{{- if .Values.datasources.openstack.sso.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cortex-cinder-openstack-sso
data:
  cert: {{ .Values.datasources.openstack.sso.cert | b64enc | quote }}
  key: {{ .Values.datasources.openstack.sso.key | b64enc | quote }}
  selfSigned: {{ .Values.datasources.openstack.sso.selfSigned | b64enc | quote }}
{{- end }}
