//go:build !ignore_autogenerated

// Copyright 2025 SAP SE
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/resource"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeReservation) DeepCopyInto(out *ComputeReservation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeReservation.
func (in *ComputeReservation) DeepCopy() *ComputeReservation {
	if in == nil {
		return nil
	}
	out := new(ComputeReservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComputeReservation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeReservationList) DeepCopyInto(out *ComputeReservationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ComputeReservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeReservationList.
func (in *ComputeReservationList) DeepCopy() *ComputeReservationList {
	if in == nil {
		return nil
	}
	out := new(ComputeReservationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComputeReservationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeReservationSchedulerSpec) DeepCopyInto(out *ComputeReservationSchedulerSpec) {
	*out = *in
	if in.CortexNova != nil {
		in, out := &in.CortexNova, &out.CortexNova
		*out = new(ComputeReservationSchedulerSpecCortexNova)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeReservationSchedulerSpec.
func (in *ComputeReservationSchedulerSpec) DeepCopy() *ComputeReservationSchedulerSpec {
	if in == nil {
		return nil
	}
	out := new(ComputeReservationSchedulerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeReservationSchedulerSpecCortexNova) DeepCopyInto(out *ComputeReservationSchedulerSpecCortexNova) {
	*out = *in
	if in.FlavorExtraSpecs != nil {
		in, out := &in.FlavorExtraSpecs, &out.FlavorExtraSpecs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeReservationSchedulerSpecCortexNova.
func (in *ComputeReservationSchedulerSpecCortexNova) DeepCopy() *ComputeReservationSchedulerSpecCortexNova {
	if in == nil {
		return nil
	}
	out := new(ComputeReservationSchedulerSpecCortexNova)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeReservationSpec) DeepCopyInto(out *ComputeReservationSpec) {
	*out = *in
	in.Scheduler.DeepCopyInto(&out.Scheduler)
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = make(map[string]resource.Quantity, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeReservationSpec.
func (in *ComputeReservationSpec) DeepCopy() *ComputeReservationSpec {
	if in == nil {
		return nil
	}
	out := new(ComputeReservationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeReservationStatus) DeepCopyInto(out *ComputeReservationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeReservationStatus.
func (in *ComputeReservationStatus) DeepCopy() *ComputeReservationStatus {
	if in == nil {
		return nil
	}
	out := new(ComputeReservationStatus)
	in.DeepCopyInto(out)
	return out
}
