//go:build !ignore_autogenerated

// Copyright 2025 SAP SE
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeReservation) DeepCopyInto(out *ComputeReservation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeReservation.
func (in *ComputeReservation) DeepCopy() *ComputeReservation {
	if in == nil {
		return nil
	}
	out := new(ComputeReservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComputeReservation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeReservationList) DeepCopyInto(out *ComputeReservationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ComputeReservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeReservationList.
func (in *ComputeReservationList) DeepCopy() *ComputeReservationList {
	if in == nil {
		return nil
	}
	out := new(ComputeReservationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComputeReservationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeReservationSpec) DeepCopyInto(out *ComputeReservationSpec) {
	*out = *in
	in.Instance.DeepCopyInto(&out.Instance)
	in.BareResource.DeepCopyInto(&out.BareResource)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeReservationSpec.
func (in *ComputeReservationSpec) DeepCopy() *ComputeReservationSpec {
	if in == nil {
		return nil
	}
	out := new(ComputeReservationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeReservationSpecBareResource) DeepCopyInto(out *ComputeReservationSpecBareResource) {
	*out = *in
	out.CPU = in.CPU.DeepCopy()
	out.Memory = in.Memory.DeepCopy()
	out.Disk = in.Disk.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeReservationSpecBareResource.
func (in *ComputeReservationSpecBareResource) DeepCopy() *ComputeReservationSpecBareResource {
	if in == nil {
		return nil
	}
	out := new(ComputeReservationSpecBareResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeReservationSpecInstance) DeepCopyInto(out *ComputeReservationSpecInstance) {
	*out = *in
	out.Memory = in.Memory.DeepCopy()
	out.VCPUs = in.VCPUs.DeepCopy()
	out.Disk = in.Disk.DeepCopy()
	if in.ExtraSpecs != nil {
		in, out := &in.ExtraSpecs, &out.ExtraSpecs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeReservationSpecInstance.
func (in *ComputeReservationSpecInstance) DeepCopy() *ComputeReservationSpecInstance {
	if in == nil {
		return nil
	}
	out := new(ComputeReservationSpecInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeReservationStatus) DeepCopyInto(out *ComputeReservationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeReservationStatus.
func (in *ComputeReservationStatus) DeepCopy() *ComputeReservationStatus {
	if in == nil {
		return nil
	}
	out := new(ComputeReservationStatus)
	in.DeepCopyInto(out)
	return out
}
