//go:build !ignore_autogenerated

// Copyright 2025 SAP SE
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDecision) DeepCopyInto(out *ComputeDecision) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDecision.
func (in *ComputeDecision) DeepCopy() *ComputeDecision {
	if in == nil {
		return nil
	}
	out := new(ComputeDecision)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComputeDecision) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDecisionFactorStatus) DeepCopyInto(out *ComputeDecisionFactorStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDecisionFactorStatus.
func (in *ComputeDecisionFactorStatus) DeepCopy() *ComputeDecisionFactorStatus {
	if in == nil {
		return nil
	}
	out := new(ComputeDecisionFactorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDecisionList) DeepCopyInto(out *ComputeDecisionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ComputeDecision, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDecisionList.
func (in *ComputeDecisionList) DeepCopy() *ComputeDecisionList {
	if in == nil {
		return nil
	}
	out := new(ComputeDecisionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComputeDecisionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDecisionPipelineOutputSpec) DeepCopyInto(out *ComputeDecisionPipelineOutputSpec) {
	*out = *in
	if in.Weights != nil {
		in, out := &in.Weights, &out.Weights
		*out = make(map[string]float64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDecisionPipelineOutputSpec.
func (in *ComputeDecisionPipelineOutputSpec) DeepCopy() *ComputeDecisionPipelineOutputSpec {
	if in == nil {
		return nil
	}
	out := new(ComputeDecisionPipelineOutputSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDecisionPipelineSpec) DeepCopyInto(out *ComputeDecisionPipelineSpec) {
	*out = *in
	if in.Outputs != nil {
		in, out := &in.Outputs, &out.Outputs
		*out = make([]ComputeDecisionPipelineOutputSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDecisionPipelineSpec.
func (in *ComputeDecisionPipelineSpec) DeepCopy() *ComputeDecisionPipelineSpec {
	if in == nil {
		return nil
	}
	out := new(ComputeDecisionPipelineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDecisionSpec) DeepCopyInto(out *ComputeDecisionSpec) {
	*out = *in
	in.Pipeline.DeepCopyInto(&out.Pipeline)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDecisionSpec.
func (in *ComputeDecisionSpec) DeepCopy() *ComputeDecisionSpec {
	if in == nil {
		return nil
	}
	out := new(ComputeDecisionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeDecisionStatus) DeepCopyInto(out *ComputeDecisionStatus) {
	*out = *in
	if in.Factors != nil {
		in, out := &in.Factors, &out.Factors
		*out = make([]ComputeDecisionFactorStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeDecisionStatus.
func (in *ComputeDecisionStatus) DeepCopy() *ComputeDecisionStatus {
	if in == nil {
		return nil
	}
	out := new(ComputeDecisionStatus)
	in.DeepCopyInto(out)
	return out
}
