# Copyright 2025 SAP SE
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: cortex-mqtt
description: MQTT setup for Cortex.
type: application
version: 0.0.2
appVersion: "0.1.0"
dependencies:
  # Owner info adds a configmap to the kubernetes cluster with information on
  # the service owner. This makes it easier to find out who to contact in case
  # of issues. See: https://github.com/sapcc/helm-charts/pkgs/container/helm-charts%2Fowner-info
  - name: owner-info
    repository: oci://ghcr.io/sapcc/helm-charts
    version: 1.0.0
  # RabbitMQ is a message broker, see: https://artifacthub.io/packages/helm/bitnami/rabbitmq
  - name: rabbitmq
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 16.0.8
