# Copyright 2025 SAP SE
# SPDX-License-Identifier: Apache-2.0

# Can be used to override the chart name (e.g. cortex-nova).
fullnameOverride: ""
nameOverride: ""

alerts:
  enabled: true
  prometheus: openstack
  componentPrefix:
