# Copyright 2025 SAP SE
# SPDX-License-Identifier: Apache-2.0

owner-info:
  helm-chart-url: "https://github.com/cobaltcore-dev/cortex/helm/cortex"
  maintainers:
    - "p.matthes@sap.com"
  support-group: "cobaltcore-dev"
  enabled: true
