kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cortex-home
nodes:
  - role: worker
  - role: control-plane
    extraPortMappings:
    - containerPort: 6443
      hostPort: 8443
    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        apiServer:
          extraArgs:
            service-account-issuer: "https://host.docker.internal:8443"
            service-account-jwks-uri: "https://host.docker.internal:8443/openid/v1/jwks"
          certSANs:
            - api-proxy
            - api-proxy.default.svc
            - api-proxy.default.svc.cluster.local
            - localhost
            - 127.0.0.1
            - host.docker.internal
