kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cortex-remote
nodes:
  - role: control-plane
    extraPortMappings:
    - containerPort: 6443
      hostPort: 8444
    extraMounts:
      - hostPath: /tmp/root-ca-home.pem
        containerPath: /etc/ca-certificates/root-ca.pem
    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        apiServer:
          extraArgs:
            oidc-client-id: "https://host.docker.internal:8443" # = audience
            oidc-issuer-url: "https://host.docker.internal:8443"
            oidc-username-claim: sub
            oidc-ca-file: /etc/ca-certificates/root-ca.pem
          certSANs:
            - api-proxy
            - api-proxy.default.svc
            - api-proxy.default.svc.cluster.local
            - localhost
            - 127.0.0.1
            - host.docker.internal