# Copyright 2025 SAP SE
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Pod
metadata:
  name: {{ $.Chart.Name }}-cli
  labels:
    app: {{ $.Chart.Name }}-cli
    {{- include "cortex.labels" $ | nindent 4 }}
spec:
  {{- with $.Values.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  securityContext:
    {{- toYaml $.Values.podSecurityContext | nindent 4 }}
  containers:
    - name: {{ $.Chart.Name }}-cli
      command:
        - "/bin/sh"
        - "-c"
        - "echo 'Waiting for commands...' && sleep infinity"
      securityContext:
        {{- toYaml $.Values.securityContext | nindent 8 }}
      image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
      imagePullPolicy: {{ $.Values.image.pullPolicy }}
      resources:
        {{- toYaml $.Values.resources | nindent 8 }}
      volumeMounts:
        - name: {{ include "cortex.fullname" $ }}-config-volume
          mountPath: /etc/config
        {{- with $.Values.volumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
  volumes:
    - name: {{ include "cortex.fullname" $ }}-config-volume
      configMap:
        name: {{ include "cortex.fullname" $ }}-config
    {{- with $.Values.volumes }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $.Values.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $.Values.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $.Values.tolerations }}
  tolerations:
    {{- toYaml . | nindent 4 }}
  {{- end }}