# Copyright 2025 SAP SE
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cortex.fullname" . }}-config
data:
  conf.yaml: |-
{{ include "cortex/templates/_conf.yaml.tpl" . | nindent 4 }}