# Copyright 2025 SAP SE
# SPDX-License-Identifier: Apache-2.0

# Declare a hook that migrates the database after a Helm upgrade.
# See: https://helm.sh/docs/topics/charts_hooks/
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "cortex.fullname" $ }}-migrations
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "cortex.fullname" $ }}-migrations
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      annotations:
        {{- with $.Values.migrationsJob.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      restartPolicy: Never
      containers:
        - name: {{ include "cortex.fullname" $ }}-migrations
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          args: ["migrate"]
          volumeMounts:
            # Custom config that can override some values, e.g. conf validation.
            - name: {{ include "cortex.fullname" $ }}-pre-upgrade-config-volume
              mountPath: /etc/config
            - name: {{ $.Chart.Name }}-secrets-volume
              mountPath: /etc/secrets
              readOnly: true
      volumes:
        - name: {{ include "cortex.fullname" $ }}-pre-upgrade-config-volume
          configMap:
            name: {{ include "cortex.fullname" $ }}-pre-upgrade-config
        - name: {{ $.Chart.Name }}-secrets-volume
          secret:
            secretName: {{ include "cortex.fullname" $ }}-secrets