# Copyright 2025 SAP SE
# SPDX-License-Identifier: Apache-2.0

{{- if index .Values "vernemq" "enabled" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cortex-mqtt
data:
  DOCKER_VERNEMQ_ACCEPT_EULA: "yes"
  DOCKER_VERNEMQ_ALLOW_REGISTER_DURING_NETSPLIT: "on"
  DOCKER_VERNEMQ_ALLOW_PUBLISH_DURING_NETSPLIT: "on"
  DOCKER_VERNEMQ_ALLOW_SUBSCRIBE_DURING_NETSPLIT: "on"
  DOCKER_VERNEMQ_ALLOW_UNSUBSCRIBE_DURING_NETSPLIT: "on"
  DOCKER_VERNEMQ_ALLOW_ANONYMOUS: "off"
  DOCKER_VERNEMQ_MAX_ONLINE_MESSAGES: "10000"
  DOCKER_VERNEMQ_MAX_OFFLINE_MESSAGES: "-1"
  DOCKER_VERNEMQ_USER_{{ .Values.vernemq.username }}: "{{ .Values.vernemq.password }}"
  DOCKER_VERNEMQ_LISTENER__TCP__LOCALHOST: "127.0.0.1:1883"
  DOCKER_VERNEMQ_LISTENER__WS__LOCALHOST: "127.0.0.1:8080"
{{- end }}