# Copyright 2025 SAP SE
# SPDX-License-Identifier: Apache-2.0

{{- range .Values.modes }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Chart.Name }}-{{ .name }}
  labels:
    {{- include "cortex.labels" $ | nindent 4 }}
    # This label will be added to the prometheus metrics.
    component: {{ $.Chart.Name }}-{{ .name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $.Values.conf.api.port }}
      targetPort: api
      protocol: TCP
      name: api
    - port: {{ $.Values.conf.monitoring.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app: {{ $.Chart.Name }}-{{ .name }}
{{- end }}