# Copyright 2025 SAP SE
# SPDX-License-Identifier: Apache-2.0

{{- range .Values.modes }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Chart.Name }}-{{ .name }}
  labels:
    {{- include "cortex.labels" $ | nindent 4 }}
    cortex.mode: {{ .name }}
spec:
  type: {{ .service.type }}
  ports:
    {{- if .service.apiPort }}
    - port: {{ .service.apiPort }}
      targetPort: api
      protocol: TCP
      name: api
    {{- end }}
    - port: {{ .service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app: {{ $.Chart.Name }}-{{ .name }}
{{- end }}