groups:
- name: cortex-cinder-alerts
  rules:
  - alert: CortexCinderInitialPlacementDown
    expr: |
      up{component="cortex-cinder-scheduler", namespace="cortex-cinder"} != 1 or
      absent(up{component="cortex-cinder-scheduler", namespace="cortex-cinder"})
    for: 5m
    labels:
      context: liveness
      dashboard: cortex/cortex
      service: cortex
      severity: warning
      support_group: workload-management
      playbook: docs/support/playbook/cortex/down
    annotations:
      summary: "Cortex initial placement for Cinder is down"
      description: >
        The Cortex initial placement is down. Initial placement requests from Cinder will
        not be served. This is no immediate problem, since Cinder will continue
        placing new volumes. However, the placement will be less desirable.
