# Copyright 2025 SAP SE
# SPDX-License-Identifier: Apache-2.0

postgresql:
  fullnameOverride: cortex-postgresql
  volumePermissions:
    enabled: true
  auth:
    postgresPassword: secret
  service:
    ports:
      postgresql: 5432

owner-info:
  helm-chart-url: "https://github.com/cobaltcore-dev/cortex/helm/postgres"
  maintainers:
    - "p.matthes@sap.com"
  support-group: "cobaltcore-dev"
  enabled: true