# Copyright 2025 SAP SE
# SPDX-License-Identifier: Apache-2.0

owner-info:
  helm-chart-url: "https://github.com/cobaltcore-dev/cortex/helm/cortex-postgres"
  maintainers:
    - "p.matthes@sap.com"
    - "markus.wieland@sap.com"
    - "arno.uhlig@sap.com"
  support-group: "cobaltcore-dev"
  enabled: true

postgresql:
  architecture: replication
  readReplicas:
    replicaCount: 2

  fullnameOverride: cortex-postgresql
  volumePermissions:
    enabled: true
  auth:
    postgresPassword: secret
    replicationPassword: secret
  service:
    ports:
      postgresql: 5432
