# Copyright 2025 SAP SE
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cortex.fullname" . }}-config
data:
  conf.json: |-
    {{- if .Values.conf }}
    {{ toJson .Values.conf }}
    {{- else }}
    {}
    {{- end }}
---
# Configmap for pre-upgrade resources.
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cortex.fullname" . }}-pre-upgrade-config
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
data:
  conf.json: |-
    {{- if .Values.conf }}
    {{ toJson .Values.conf }}
    {{- else }}
    {}
    {{- end }}
