# Copyright 2025 SAP SE
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cortex.fullname" . }}-config
data:
  conf.json: |-
    {{- $mergedConf := dict }}
    {{- if .Values.global.conf }}
    {{- $mergedConf = .Values.global.conf }}
    {{- end }}
    {{- if .Values.conf }}
    {{- $mergedConf = mergeOverwrite .Values.conf $mergedConf }}
    {{- end }}
    {{ toJson $mergedConf }}
---
# Configmap for pre-upgrade resources.
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cortex.fullname" . }}-pre-upgrade-config
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
data:
  conf.json: |-
    {{- $mergedConf := dict }}
    {{- if .Values.global.conf }}
    {{- $mergedConf = .Values.global.conf }}
    {{- end }}
    {{- if .Values.conf }}
    {{- $mergedConf = mergeOverwrite .Values.conf $mergedConf }}
    {{- end }}
    {{ toJson $mergedConf }}
