# Copyright 2025 SAP SE
# SPDX-License-Identifier: Apache-2.0

{{- range .Values.modes }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cortex.fullname" $ }}-{{ .name }}
  annotations:
    # Roll the service when its configmap or secret change.
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") $ | sha256sum }}
    checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") $ | sha256sum }}
    checksum/image: "{{ $.Values.image.tag }}"
    kubectl.kubernetes.io/default-container: {{ include "cortex.fullname" $ }}-{{ .name }}
  labels:
    app: {{ include "cortex.fullname" $ }}-{{ .name }}
    {{- include "cortex.labels" $ | nindent 4 }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      {{- include "cortex.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "cortex.fullname" $ }}-{{ .name }}
        {{- include "cortex.labels" $ | nindent 8 }}
    spec:
      serviceAccountName: {{ $.Release.Namespace }}-{{ include "cortex.fullname" $ }}
      containers:
        - name: {{ include "cortex.fullname" $ }}-{{ .name }}
          args: {{ .args | toJson }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          resources:
            requests:
              memory: {{ $.Values.resources.requests.memory }}
              cpu: {{ $.Values.resources.requests.cpu }}
            limits:
              memory: {{ $.Values.resources.limits.memory }}
              cpu: {{ $.Values.resources.limits.cpu }}
          ports:
            - name: api
              containerPort: {{ $.Values.conf.api.port }}
              protocol: TCP
            - name: metrics
              containerPort: {{ $.Values.conf.monitoring.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml $.Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml $.Values.readinessProbe | nindent 12 }}
          volumeMounts:
            - name: {{ include "cortex.fullname" $ }}-config-volume
              mountPath: /etc/config
            - name: {{ include "cortex.fullname" $ }}-secrets-volume
              mountPath: /etc/secrets
              readOnly: true
      volumes:
        - name: {{ include "cortex.fullname" $ }}-config-volume
          configMap:
            name: {{ include "cortex.fullname" $ }}-config
        - name: {{ include "cortex.fullname" $ }}-secrets-volume
          secret:
            secretName: {{ include "cortex.fullname" $ }}-secrets
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cortex.fullname" $ }}-cli
  labels:
    app: {{ include "cortex.fullname" $ }}-cli
    {{- include "cortex.labels" $ | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "cortex.fullname" $ }}-cli
  template:
    metadata:
      labels:
        app: {{ include "cortex.fullname" $ }}-cli
        {{- include "cortex.labels" $ | nindent 8 }}
    spec:
      serviceAccountName: {{ .Release.Namespace }}-{{ include "cortex.fullname" $ }}
      containers:
        - name: {{ include "cortex.fullname" $ }}-cli
          command:
            - "/bin/sh"
            - "-c"
            - "echo 'Waiting for commands...' && sleep infinity"
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          volumeMounts:
            - name: {{ include "cortex.fullname" $ }}-config-volume
              mountPath: /etc/config
            - name: {{ include "cortex.fullname" $ }}-secrets-volume
              mountPath: /etc/secrets
              readOnly: true
      volumes:
        - name: {{ include "cortex.fullname" $ }}-config-volume
          configMap:
            name: {{ include "cortex.fullname" $ }}-config
        - name: {{ include "cortex.fullname" $ }}-secrets-volume
          secret:
            secretName: {{ include "cortex.fullname" $ }}-secrets
