# Copyright 2025 SAP SE
# SPDX-License-Identifier: Apache-2.0

# Declare a hook that migrates the database after a Helm upgrade.
# See: https://helm.sh/docs/topics/charts_hooks/
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "cortex.fullname" $ }}-migrations
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: {{ include "cortex.fullname" $ }}-migrations
      annotations:
        {{- with $.Values.migrationsJob.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      restartPolicy: Never
      containers:
        - name: {{ include "cortex.fullname" $ }}-migrations
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          args: ["migrate"]
          resources:
            requests:
              memory: {{ .Values.migrationsJob.resources.requests.memory }}
              cpu: {{ .Values.migrationsJob.resources.requests.cpu }}
            limits:
              memory: {{ .Values.migrationsJob.resources.limits.memory }}
              cpu: {{ .Values.migrationsJob.resources.limits.cpu }}
          volumeMounts:
            # Custom config that can override some values, e.g. conf validation.
            - name: {{ include "cortex.fullname" $ }}-pre-upgrade-config-volume
              mountPath: /etc/config
            - name: {{ $.Chart.Name }}-pre-upgrade-secrets-volume
              mountPath: /etc/secrets
              readOnly: true
      volumes:
        - name: {{ include "cortex.fullname" $ }}-pre-upgrade-config-volume
          configMap:
            name: {{ include "cortex.fullname" $ }}-pre-upgrade-config
        - name: {{ $.Chart.Name }}-pre-upgrade-secrets-volume
          secret:
            secretName: {{ include "cortex.fullname" $ }}-pre-upgrade-secrets