# Copyright 2025 SAP SE
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cortex.fullname" . }}-secrets
type: Opaque
data:
  secrets.json: |-
    {{- $mergedSecrets := dict }}
    {{- if .Values.global.secrets }}
    {{- $mergedSecrets = .Values.global.secrets }}
    {{- end }}
    {{- if .Values.secrets }}
    {{- $mergedSecrets = mergeOverwrite .Values.secrets $mergedSecrets }}
    {{- end }}
    {{ toJson $mergedSecrets | b64enc }}
---
# Secret for pre-upgrade resources.
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cortex.fullname" . }}-pre-upgrade-secrets
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
type: Opaque
data:
  secrets.json: |-
    {{- $mergedSecrets := dict }}
    {{- if .Values.global.secrets }}
    {{- $mergedSecrets = .Values.global.secrets }}
    {{- end }}
    {{- if .Values.secrets }}
    {{- $mergedSecrets = mergeOverwrite .Values.secrets $mergedSecrets }}
    {{- end }}
    {{ toJson $mergedSecrets | b64enc }}
