# Copyright 2025 SAP SE
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cortex-vis
  labels:
    app: cortex-vis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cortex-vis
  template:
    metadata:
      labels:
        app: cortex-vis
    spec:
      containers:
        - name: cortex-vis # from local tilt build
          image: cortex-vis
          ports:
            - containerPort: 80