---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - knowledge.cortex
  resources:
  - knowledges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - knowledge.cortex
  resources:
  - knowledges/finalizers
  verbs:
  - update
- apiGroups:
  - knowledge.cortex
  resources:
  - knowledges/status
  verbs:
  - get
  - patch
  - update
