{
 "title": "Cortex Scheduling",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Initial Placement (Scheduler)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pipeline: nova-external-scheduler-*",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pipeline: manila-external-scheduler",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Nova: from which idx the selected host came from",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum(delta(cortex_scheduler_pipeline_step_shift_origin_bucket{outidx=\"0\",pipeline=~\"nova-external-scheduler-.*\"}[2m]) / 2) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Manila: from which idx the selected host came from",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "sum(delta(cortex_scheduler_pipeline_step_shift_origin_bucket{outidx=\"0\",pipeline=\"manila-external-scheduler\"}[2m]) / 2) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Nova: selected host origin idx (rate over 2min)",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_scheduler_pipeline_step_shift_origin_bucket{outidx=\"0\",pipeline=~\"nova-external-scheduler-.*\"}[2m])) by (le, step, alias))",
     "legendFormat": "{{ step }} {{ alias }}"
    }
   ]
  },
  {
   "title": "Manila: selected host origin idx (rate over 2min)",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_scheduler_pipeline_step_shift_origin_bucket{outidx=\"0\",pipeline=\"manila-external-scheduler\"}[2m])) by (le, step, alias))",
     "legendFormat": "{{ step }} {{ alias }}"
    }
   ]
  },
  {
   "title": "Nova scheduler impact",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_scheduler_pipeline_step_impact_bucket{pipeline=~\"nova-external-scheduler-.*\"}[2m])) by (le, step, alias, stat, unit))",
     "legendFormat": "{{stat}} {{unit}} ({{step}} {{alias}})"
    }
   ]
  },
  {
   "title": "Manila scheduler impact",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_scheduler_pipeline_step_impact_bucket{pipeline=\"manila-external-scheduler\"}[2m])) by (le, step, stat, unit))",
     "legendFormat": "{{stat}} {{unit}} ({{step}})"
    }
   ]
  },
  {
   "title": "Requests by type (rate over 2min)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by(pipeline) (rate(cortex_scheduler_pipeline_requests_total{}[2m]))",
     "legendFormat": "Pipeline: {{pipeline}}"
    }
   ]
  },
  {
   "title": "Time needed to run scheduler steps",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_scheduler_pipeline_step_run_duration_seconds_bucket[2m])) by (le, step, alias, pipeline))",
     "legendFormat": "{{pipeline}} {{step}} ({{alias}})"
    }
   ]
  },
  {
   "title": "Time needed to run select queries for scheduler",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_db_select_duration_seconds_bucket{group=~\"scheduler-.+\"}[2m])) by (le, group, query))",
     "legendFormat": "{{group}} {{query}}"
    }
   ]
  },
  {
   "title": "Successful request rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cortex_scheduler_api_request_duration_seconds_count{status=~\"2.+\"}[2m])) by (method, path, status, error)",
     "legendFormat": "{{method}} {{path}} {{status}} {{error}}"
    }
   ]
  },
  {
   "title": "Error request rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cortex_scheduler_api_request_duration_seconds_count{status=~\"4.+|5.+\"}[2m])) by (method, path, status, error)",
     "legendFormat": "{{method}} {{path}} {{status}} {{error}}"
    }
   ]
  },
  {
   "title": "Average response time (success)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_scheduler_api_request_duration_seconds_bucket{status=~\"2.+\"}[2m])) by (le, method, path, status, error))",
     "legendFormat": "{{method}} {{path}} {{status}} {{error}}"
    }
   ]
  },
  {
   "title": "Average response time (error)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_scheduler_api_request_duration_seconds_bucket{status=~\"4.+|5.+\"}[2m])) by (le, method, path, status, error))",
     "legendFormat": "{{method}} {{path}} {{status}} {{error}}"
    }
   ]
  },
  {
   "title": "Weight modifications",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pipeline, subject, step, alias) (delta(cortex_scheduler_pipeline_step_weight_modification[2m]))",
     "legendFormat": "{{ pipeline }} {{ subject }} {{ step }} ({{ alias }})"
    }
   ]
  }
 ]
}