{
 "title": "Cortex VMware Infrastructure - Compute",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "availability_zone",
    "label": "Availability Zone",
    "query": {
     "query": "label_values(cortex_vmware_host_capacity_available, availability_zone)"
    }
   },
   {
    "name": "hypervisor_family",
    "label": "Hypervisor Family",
    "query": {
     "query": "label_values(cortex_vmware_host_capacity_available, hypervisor_family)"
    }
   },
   {
    "name": "compute_host",
    "label": "Compute Host",
    "query": {
     "query": "label_values(cortex_vmware_host_capacity_available, compute_host)"
    }
   },
   {
    "name": "enabled",
    "label": "Enabled",
    "query": {
     "query": "label_values(cortex_vmware_host_capacity_available, enabled)"
    }
   },
   {
    "name": "workload_type",
    "label": "Workload Type",
    "query": {
     "query": "label_values(cortex_vmware_host_capacity_available, workload_type)"
    }
   },
   {
    "name": "cpu_architecture",
    "label": "CPU Architecture",
    "query": {
     "query": "label_values(cortex_vmware_host_capacity_available, cpu_architecture)"
    }
   },
   { "name": "project_id" }
  ]
 },
 "panels": [
  {
   "title": "README",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Introduction",
     "type": "text",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "# Cortex Infrastructure Dashboard - Compute\n\nWelcome to the Cortex Infrastructure Dashboard for the compute scheduling domain of Cortex! This dashboard provides real-time insights into the current state of our data centers and their available capacity for virtual machine placement.\nThe dashboard is built on top of the Cortex Knowledge Database, with all metrics directly exported by Cortex. This ensures that the data you see here is exactly the same data used for our actual scheduling decisions.\n\nThis dashboard is still under active development. We welcome your feedback and contributions! Please feel free to reach out to use if you want to contribute or have suggestions for improvements.\n\nThe data displayed in this dashboard represents the available capacity of each hypervisor with the following important considerations:\n\n- **Includes overcommits** - The capacity values reflect overcommitted resources as configured in the system.\n- **Failover capacity limitations** - Failover capacity is automatically excluded from the displayed values, meaning the capacity you see is what's actually available for new VM placements. However, we cannot currently show you how much capacity is being reserved for failover scenarios.\n- **Commitments not included** - The displayed capacity does not yet account for resource commitments, so this is not the final available capacity for scheduling decisions\n\n## Filters\n\n| Filter | Description |\n|--------|-------------|\n| **Availability Zone** | See the whole region or filter by specific availability zones |\n| **Hypervisor Family** | Filter by virtualization platform (KVM, VMware) |\n| **Specific Hypervisors** | Drill down to individual hypervisors |\n| **Enabled** | TODO |\n| **Workload Type** | Workload type that is supposed to run on this hypervisor. General Purpose, HANA |\n| **CPU Architecture** | CPU Architecture of the hypervisor. Cascade Lake, Sapphire Rapids |\n| **Project ID** | Filter the capacity for a specific projects. This does then include all hypervisors that allow every project as well as hypervisors that are dedicated to the specific project. |\n\n## Structure\n\nThe dashboard is organized into two main sections to provide both quick insights and detailed analysis capabilities:\n\n### Pre-filtered Sections\n\nAt the top of the dashboard, you'll find 4 pre-configured sections that represent the most common combinations of workload type and CPU architecture:\n\nThese sections are designed to save you time by eliminating the need to manually apply workload type and CPU architecture filters every time you open the dashboard. Obviously the filters for workload type and cpu architecture are already applied, but you can still use additional filters (Availability Zone, Hypervisor Family, etc.) on top of these pre-configured views.\n\nEach pre-filtered section includes:\n\n- Time series data showing available capacity trends per resource\n- Current available capacity per resource\n- Current number of hypervisors considered in the section\n- Linear trend analysis showing projected future capacity\n\n### Custom Analysis Section\n\nBelow the pre-filtered sections, there's a flexible analysis section where you can:\n\n- Apply any combination of filters according to your specific needs\n- Access the same visualization panels as in the pre-filtered sections\n- View additional detailed information about individual hypervisors (not just aggregated values)\n"
     },
     "targets": [
      {}
     ]
    }
   ]
  },
  {
   "title": "General Purpose",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total General Purpose Capacity (with commitments, no cpu architecture distinction)",
     "type": "text",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
     "options": { "content": "\n         " },
     "targets": [
      {}
     ]
    },
    {
     "title": "Amount Hypervisors",
     "type": "stat",
     "gridPos": { "h": 11, "w": 2, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      # Use any resource here, otherwise the amount would have to be divided by 3, since the metric is exported 3 times per hypervisor (cpu, ram, disk)\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"general-purpose\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n) or on() vector(0)",
       "legendFormat": "Available"
      },
      {
       "expr": "count(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      # Use any resource here, otherwise the amount would have to be divided by 3, since the metric is exported 3 times per hypervisor (cpu, ram, disk)\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"general-purpose\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"false\"\n    }\n  )\n) or on() vector(0)",
       "legendFormat": "Disabled"
      }
     ]
    },
    {
     "title": "Available Capacity over time",
     "type": "graph",
     "gridPos": { "h": 11, "w": 7, "x": 2, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit", "label": "Capacity (%)" }
     ],
     "targets": [
      {
       "expr": "(\n  sum(\n    max by (compute_host, resource) (\n      cortex_vmware_host_capacity_available{\n        resource=\"cpu\",\n        availability_zone=~\"$availability_zone\",\n        compute_host=~\"$compute_host\",\n        hypervisor_family=~\"$hypervisor_family\",\n        workload_type=\"general-purpose\",\n        pinned_projects=~\"(^$|.*$project_id.*)\",\n        enabled=\"true\"\n      }\n    )\n  )\n  -\n  sum(\n  clamp_min(\n    max by (project_id, availability_zone) (\n      limes_project_committed_per_az{\n        service=\"compute\",\n        resource=\"cores\",\n        availability_zone=~\"$availability_zone\"  # Will not be any for compute service\n      }\n    )\n    -\n    on(project_id, availability_zone)\n    max by (project_id, availability_zone) (\n      limes_project_usage_per_az{\n        service=\"compute\",\n        resource=\"cores\",\n        availability_zone=~\"$availability_zone\"\n      }\n    ),\n    0\n  )\n  or\n  max by (project_id, availability_zone) (\n      limes_project_committed_per_az{\n        service=\"compute\",\n        resource=\"cores\",\n        availability_zone=~\"$availability_zone\"  # Will not be any for compute service\n      }\n    )\n)\n) \n/ \nsum(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"general-purpose\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)",
       "legendFormat": "vCPU Capacity"
      },
      {
       "expr": "(\n  sum(\n    max by (compute_host, resource) (\n      cortex_vmware_host_capacity_available{\n        resource=\"ram\",\n        availability_zone=~\"$availability_zone\",\n        compute_host=~\"$compute_host\",\n        hypervisor_family=~\"$hypervisor_family\",\n        workload_type=\"general-purpose\",\n        pinned_projects=~\"(^$|.*$project_id.*)\",\n        enabled=\"true\"\n      }\n    )\n  )\n  -\n  sum(\n  clamp_min(\n    max by (project_id, availability_zone) (\n      limes_project_committed_per_az{\n        service=\"compute\",\n        resource=\"ram\",\n        availability_zone=~\"$availability_zone\"  # Will not be any for compute service\n      }\n    )\n    -\n    on(project_id, availability_zone)\n    max by (project_id, availability_zone) (\n      limes_project_usage_per_az{\n        service=\"compute\",\n        resource=\"ram\",\n        availability_zone=~\"$availability_zone\"\n      }\n    ),\n    0\n  )\n  or\n  max by (project_id, availability_zone) (\n      limes_project_committed_per_az{\n        service=\"compute\",\n        resource=\"ram\",\n        availability_zone=~\"$availability_zone\"  # Will not be any for compute service\n      }\n    )\n)\n) \n/ \nsum(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"general-purpose\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)",
       "legendFormat": "RAM Capacity"
      },
      {
       "expr": "count(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      # Use any resource here, otherwise the amount would have to be divided by 3, since the metric is exported 3 times per hypervisor (cpu, ram, disk)\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"general-purpose\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)",
       "legendFormat": "Active hypervisors"
      }
     ]
    },
    {
     "title": "vCPUs",
     "type": "stat",
     "gridPos": { "h": 11, "w": 8, "x": 9, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  clamp_min(\n    max by (project_id, availability_zone) (\n      limes_project_committed_per_az{\n        service=\"compute\",\n        resource=\"cores\",\n        availability_zone=~\"$availability_zone\"  # Will not be any for compute service\n      }\n    )\n    -\n    on(project_id, availability_zone)\n    max by (project_id, availability_zone) (\n      limes_project_usage_per_az{\n        service=\"compute\",\n        resource=\"cores\",\n        availability_zone=~\"$availability_zone\"\n      }\n    ),\n    0\n  )\n  or\n  max by (project_id, availability_zone) (\n      limes_project_committed_per_az{\n        service=\"compute\",\n        resource=\"cores\",\n        availability_zone=~\"$availability_zone\"  # Will not be any for compute service\n      }\n    )\n)",
       "legendFormat": "vCPU"
      },
      {},
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"general-purpose\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)\n",
       "legendFormat": "Available (without commitments)"
      },
      {
       "expr": "sum(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"general-purpose\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "RAM",
     "type": "stat",
     "gridPos": { "h": 11, "w": 7, "x": 17, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  clamp_min(\n    max by (project_id, availability_zone) (\n      limes_project_committed_per_az{\n        service=\"compute\",\n        resource=\"ram\",\n        availability_zone=~\"$availability_zone\"  # Will not be any for compute service\n      }\n    )\n    -\n    on(project_id, availability_zone)\n    max by (project_id, availability_zone) (\n      limes_project_usage_per_az{\n        service=\"compute\",\n        resource=\"ram\",\n        availability_zone=~\"$availability_zone\"\n      }\n    ),\n    0\n  )\n  or\n  max by (project_id, availability_zone) (\n      limes_project_committed_per_az{\n        service=\"compute\",\n        resource=\"ram\",\n        availability_zone=~\"$availability_zone\"  # Will not be any for compute service\n      }\n    )\n)",
       "legendFormat": "RAM"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"general-purpose\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)\n",
       "legendFormat": "Available (without commitments)"
      },
      {
       "expr": "sum(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"general-purpose\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Committed - Usage per project",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "max by (project_id, availability_zone) (\n  limes_project_committed_per_az{service=\"compute\",resource=\"cores\",availability_zone=~\"$availability_zone\"}\n)"
      },
      {
       "expr": "max by (project_id, availability_zone) (\n  limes_project_usage_per_az{service=\"compute\",resource=\"cores\",availability_zone=~\"$availability_zone\"}\n)"
      },
      {
       "expr": "max by (project_id, availability_zone) (\n  limes_project_usage_per_az{service=\"compute\",resource=\"ram\",availability_zone=~\"$availability_zone\"}\n)"
      },
      {
       "expr": "max by (project_id, availability_zone) (\n  limes_project_committed_per_az{service=\"compute\",resource=\"ram\",availability_zone=~\"$availability_zone\"}\n)"
      },
      {
       "expr": "  clamp_min(\n    max by (project_id, availability_zone) (\n      limes_project_committed_per_az{\n        service=\"compute\",\n        resource=\"cores\",\n        availability_zone=~\"$availability_zone\"  # Will not be any for compute service\n      }\n    )\n    -\n    on(project_id, availability_zone)\n    max by (project_id, availability_zone) (\n      limes_project_usage_per_az{\n        service=\"compute\",\n        resource=\"cores\",\n        availability_zone=~\"$availability_zone\"\n      }\n    ),\n    0\n  )\n  or\n  max by (project_id, availability_zone) (\n      limes_project_committed_per_az{\n        service=\"compute\",\n        resource=\"cores\",\n        availability_zone=~\"$availability_zone\"  # Will not be any for compute service\n      }\n    )"
      },
      {
       "expr": "  clamp_min(\n    max by (project_id, availability_zone) (\n      limes_project_committed_per_az{\n        service=\"compute\",\n        resource=\"ram\",\n        availability_zone=~\"$availability_zone\"  # Will not be any for compute service\n      }\n    )\n    -\n    on(project_id, availability_zone)\n    max by (project_id, availability_zone) (\n      limes_project_usage_per_az{\n        service=\"compute\",\n        resource=\"ram\",\n        availability_zone=~\"$availability_zone\"\n      }\n    ),\n    0\n  )\n  or\n  max by (project_id, availability_zone) (\n      limes_project_committed_per_az{\n        service=\"compute\",\n        resource=\"ram\",\n        availability_zone=~\"$availability_zone\"  # Will not be any for compute service\n      }\n    )"
      }
     ]
    },
    {
     "title": "Cascade Lake (without commitments)",
     "type": "text",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {}
     ]
    },
    {
     "title": "Amount Hypervisors",
     "type": "stat",
     "gridPos": { "h": 11, "w": 2, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      # Use any resource here, otherwise the amount would have to be divided by 3, since the metric is exported 3 times per hypervisor (cpu, ram, disk)\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"cascade-lake\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n) or on() vector(0)",
       "legendFormat": "Available"
      },
      {
       "expr": "count(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      # Use any resource here, otherwise the amount would have to be divided by 3, since the metric is exported 3 times per hypervisor (cpu, ram, disk)\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"cascade-lake\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"false\"\n    }\n  )\n) or on() vector(0)",
       "legendFormat": "Disabled"
      }
     ]
    },
    {
     "title": "Available Capacity over time",
     "type": "graph",
     "gridPos": { "h": 11, "w": 7, "x": 2, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit", "label": "Capacity (%)" }
     ],
     "targets": [
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"cascade-lake\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)\n",
       "legendFormat": "Available vCPU"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"cascade-lake\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)\n",
       "legendFormat": "Available RAM"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"cascade-lake\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)",
       "legendFormat": "Available Disk"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"cascade-lake\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total vCPU"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"cascade-lake\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total RAM"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"cascade-lake\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total Disk"
      },
      {
       "expr": "count(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      # Use any resource here, otherwise the amount would have to be divided by 3, since the metric is exported 3 times per hypervisor (cpu, ram, disk)\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"cascade-lake\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)",
       "legendFormat": "Active hypervisor"
      }
     ]
    },
    {
     "title": "vCPU Capacity",
     "type": "stat",
     "gridPos": { "h": 11, "w": 5, "x": 9, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"cascade-lake\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)\n",
       "legendFormat": "Available"
      },
      {
       "expr": "sum(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"cascade-lake\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total"
      },
      {
       "expr": "predict_linear(\n  sum(\n    max by (compute_host) (\n      cortex_vmware_host_capacity_available{\n        resource=\"cpu\",\n        availability_zone=~\"$availability_zone\",\n        compute_host=~\"$compute_host\",\n        hypervisor_family=~\"$hypervisor_family\",\n        workload_type=\"general-purpose\",\n        cpu_architecture=\"cascade-lake\",\n        pinned_projects=~\"(^$|.*$project_id.*)\",\n        enabled=\"true\"\n      }\n    )\n  )\n[56d:4h], 4838400)",
       "legendFormat": "Predicted Capacity"
      }
     ]
    },
    {
     "title": "RAM Capacity",
     "type": "stat",
     "gridPos": { "h": 11, "w": 5, "x": 14, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"cascade-lake\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)\n",
       "legendFormat": "Available"
      },
      {
       "expr": "sum(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"cascade-lake\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total"
      },
      {
       "expr": "predict_linear(\n  sum(\n    max by (compute_host) (\n      cortex_vmware_host_capacity_available{\n        resource=\"ram\",\n        availability_zone=~\"$availability_zone\",\n        compute_host=~\"$compute_host\",\n        hypervisor_family=~\"$hypervisor_family\",\n        workload_type=\"general-purpose\",\n        cpu_architecture=\"cascade-lake\",\n        pinned_projects=~\"(^$|.*$project_id.*)\",\n        enabled=\"true\"\n      }\n    )\n  )\n[56d:4h], 4838400)",
       "legendFormat": "Predicted Capacity"
      }
     ]
    },
    {
     "title": "Disk Capacity",
     "type": "stat",
     "gridPos": { "h": 11, "w": 5, "x": 19, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"cascade-lake\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)\n",
       "legendFormat": "Available"
      },
      {
       "expr": "sum(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"cascade-lake\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total"
      },
      {
       "expr": "predict_linear(\n  sum(\n    max by (compute_host) (\n      cortex_vmware_host_capacity_available{\n        resource=\"disk\",\n        availability_zone=~\"$availability_zone\",\n        compute_host=~\"$compute_host\",\n        hypervisor_family=~\"$hypervisor_family\",\n        workload_type=\"general-purpose\",\n        cpu_architecture=\"cascade-lake\",\n        pinned_projects=~\"(^$|.*$project_id.*)\",\n        enabled=\"true\"\n      }\n    )\n  )\n[56d:4h], 4838400)",
       "legendFormat": "Predicted Capacity"
      }
     ]
    },
    {
     "title": "Sapphire Rapids (without commitments)",
     "type": "text",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {}
     ]
    },
    {
     "title": "Amount Hypervisors",
     "type": "stat",
     "gridPos": { "h": 11, "w": 2, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      # Use any resource here, otherwise the amount would have to be divided by 3, since the metric is exported 3 times per hypervisor (cpu, ram, disk)\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"sapphire-rapids\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n) or on() vector(0)",
       "legendFormat": "Available"
      },
      {
       "expr": "count(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      # Use any resource here, otherwise the amount would have to be divided by 3, since the metric is exported 3 times per hypervisor (cpu, ram, disk)\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"sapphire-rapids\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"false\"\n    }\n  )\n) or on() vector(0)",
       "legendFormat": "Disabled"
      }
     ]
    },
    {
     "title": "Available Capacity over time",
     "type": "graph",
     "gridPos": { "h": 11, "w": 7, "x": 2, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit", "label": "Capacity (%)" }
     ],
     "targets": [
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"sapphire-rapids\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)\n",
       "legendFormat": "Available vCPU"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"sapphire-rapids\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)\n",
       "legendFormat": "Available RAM"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"sapphire-rapids\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)",
       "legendFormat": "Available Disk"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"sapphire-rapids\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total vCPU"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"sapphire-rapids\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total RAM"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"sapphire-rapids\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total Disk"
      },
      {
       "expr": "count(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      # Use any resource here, otherwise the amount would have to be divided by 3, since the metric is exported 3 times per hypervisor (cpu, ram, disk)\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"sapphire-rapids\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)",
       "legendFormat": "Active hypervisor"
      }
     ]
    },
    {
     "title": "vCPU Capacity",
     "type": "stat",
     "gridPos": { "h": 11, "w": 5, "x": 9, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"sapphire-rapids\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)\n",
       "legendFormat": "Available"
      },
      {
       "expr": "sum(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"sapphire-rapids\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total"
      },
      {
       "expr": "predict_linear(\n  sum(\n    max by (compute_host) (\n      cortex_vmware_host_capacity_available{\n        resource=\"cpu\",\n        availability_zone=~\"$availability_zone\",\n        compute_host=~\"$compute_host\",\n        hypervisor_family=~\"$hypervisor_family\",\n        workload_type=\"general-purpose\",\n        cpu_architecture=\"sapphire-rapids\",\n        pinned_projects=~\"(^$|.*$project_id.*)\",\n        enabled=\"true\"\n      }\n    )\n  )\n[56d:4h], 4838400)",
       "legendFormat": "Predicted Capacity"
      }
     ]
    },
    {
     "title": "RAM Capacity",
     "type": "stat",
     "gridPos": { "h": 11, "w": 5, "x": 14, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"sapphire-rapids\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)\n",
       "legendFormat": "Available"
      },
      {
       "expr": "sum(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"sapphire-rapids\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total"
      },
      {
       "expr": "predict_linear(\n  sum(\n    max by (compute_host) (\n      cortex_vmware_host_capacity_available{\n        resource=\"ram\",\n        availability_zone=~\"$availability_zone\",\n        compute_host=~\"$compute_host\",\n        hypervisor_family=~\"$hypervisor_family\",\n        workload_type=\"general-purpose\",\n        cpu_architecture=\"sapphire-rapids\",\n        pinned_projects=~\"(^$|.*$project_id.*)\",\n        enabled=\"true\"\n      }\n    )\n  )\n[56d:4h], 4838400)",
       "legendFormat": "Predicted Capacity"
      }
     ]
    },
    {
     "title": "Disk Capacity",
     "type": "stat",
     "gridPos": { "h": 11, "w": 5, "x": 19, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"sapphire-rapids\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)\n",
       "legendFormat": "Available"
      },
      {
       "expr": "sum(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"general-purpose\",\n      cpu_architecture=\"sapphire-rapids\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total"
      },
      {
       "expr": "predict_linear(\n  sum(\n    max by (compute_host) (\n      cortex_vmware_host_capacity_available{\n        resource=\"disk\",\n        availability_zone=~\"$availability_zone\",\n        compute_host=~\"$compute_host\",\n        hypervisor_family=~\"$hypervisor_family\",\n        workload_type=\"general-purpose\",\n        cpu_architecture=\"sapphire-rapids\",\n        pinned_projects=~\"(^$|.*$project_id.*)\",\n        enabled=\"true\"\n      }\n    )\n  )\n[56d:4h], 4838400)",
       "legendFormat": "Predicted Capacity"
      }
     ]
    }
   ]
  },
  {
   "title": "HANA | Cascade Lake",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Amount Hypervisors",
     "type": "stat",
     "gridPos": { "h": 11, "w": 2, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      # Use any resource here, otherwise the amount would have to be divided by 3, since the metric is exported 3 times per hypervisor (cpu, ram, disk)\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n) or on() vector(0)",
       "legendFormat": "Available"
      },
      {
       "expr": "count(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      # Use any resource here, otherwise the amount would have to be divided by 3, since the metric is exported 3 times per hypervisor (cpu, ram, disk)\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"false\"\n    }\n  )\n) or on() vector(0)",
       "legendFormat": "Disabled"
      }
     ]
    },
    {
     "title": "Available Capacity over time",
     "type": "graph",
     "gridPos": { "h": 11, "w": 7, "x": 2, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit", "label": "Capacity (%)" }
     ],
     "targets": [
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)\n",
       "legendFormat": "Available vCPU"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)\n",
       "legendFormat": "Available RAM"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)",
       "legendFormat": "Available Disk"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total vCPU"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total RAM"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total Disk"
      }
     ]
    },
    {
     "title": "vCPU Capacity",
     "type": "stat",
     "gridPos": { "h": 11, "w": 5, "x": 9, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)\n",
       "legendFormat": "Available"
      },
      {
       "expr": "sum(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total"
      },
      {
       "expr": "predict_linear(\n  sum(\n    max by (compute_host) (\n      cortex_vmware_host_capacity_available{\n        resource=\"cpu\",\n        availability_zone=~\"$availability_zone\",\n        compute_host=~\"$compute_host\",\n        hypervisor_family=~\"$hypervisor_family\",\n        workload_type=\"hana\",\n        cpu_architecture=\"cascade-lake\",\n        pinned_projects=~\"(^$|.*$project_id.*)\",\n        enabled=\"true\"\n      }\n    )\n  )\n[56d:4h], 4838400)",
       "legendFormat": "Predicted Capacity"
      }
     ]
    },
    {
     "title": "RAM Capacity",
     "type": "stat",
     "gridPos": { "h": 11, "w": 5, "x": 14, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)\n",
       "legendFormat": "Available"
      },
      {
       "expr": "sum(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total"
      },
      {
       "expr": "predict_linear(\n  sum(\n    max by (compute_host) (\n      cortex_vmware_host_capacity_available{\n        resource=\"ram\",\n        availability_zone=~\"$availability_zone\",\n        compute_host=~\"$compute_host\",\n        hypervisor_family=~\"$hypervisor_family\",\n        workload_type=\"hana\",\n        cpu_architecture=\"cascade-lake\",\n        pinned_projects=~\"(^$|.*$project_id.*)\",\n        enabled=\"true\"\n      }\n    )\n  )\n[56d:4h], 4838400)",
       "legendFormat": "Predicted Capacity"
      }
     ]
    },
    {
     "title": "Disk Capacity",
     "type": "stat",
     "gridPos": { "h": 11, "w": 5, "x": 19, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)\n",
       "legendFormat": "Available"
      },
      {
       "expr": "sum(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"hana\",\n      cpu_architecture=\"cascade-lake\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total"
      },
      {
       "expr": "predict_linear(\n  sum(\n    max by (compute_host) (\n      cortex_vmware_host_capacity_available{\n        resource=\"disk\",\n        availability_zone=~\"$availability_zone\",\n        compute_host=~\"$compute_host\",\n        hypervisor_family=~\"$hypervisor_family\",\n        workload_type=\"hana\",\n        cpu_architecture=\"cascade-lake\",\n        pinned_projects=~\"(^$|.*$project_id.*)\",\n        enabled=\"true\"\n      }\n    )\n  )\n[56d:4h], 4838400)",
       "legendFormat": "Predicted Capacity"
      }
     ]
    }
   ]
  },
  {
   "title": "HANA | Sapphire Rapids",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Amount Hypervisors",
     "type": "stat",
     "gridPos": { "h": 11, "w": 2, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      # Use any resource here, otherwise the amount would have to be divided by 3, since the metric is exported 3 times per hypervisor (cpu, ram, disk)\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n) or on() vector(0)",
       "legendFormat": "Available"
      },
      {
       "expr": "count(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      # Use any resource here, otherwise the amount would have to be divided by 3, since the metric is exported 3 times per hypervisor (cpu, ram, disk)\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"false\"\n    }\n  )\n) or on() vector(0)",
       "legendFormat": "Disabled"
      }
     ]
    },
    {
     "title": "Available Capacity over time",
     "type": "graph",
     "gridPos": { "h": 11, "w": 7, "x": 2, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit", "label": "Capacity (%)" }
     ],
     "targets": [
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)\n",
       "legendFormat": "Available vCPU"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)\n",
       "legendFormat": "Available RAM"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)",
       "legendFormat": "Available Disk"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total vCPU"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total RAM"
      },
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_total{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total Disk"
      },
      {
       "expr": "count(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      # Use any resource here, otherwise the amount would have to be divided by 3, since the metric is exported 3 times per hypervisor (cpu, ram, disk)\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n) ",
       "legendFormat": "Active hypervisor"
      }
     ]
    },
    {
     "title": "vCPU Capacity",
     "type": "stat",
     "gridPos": { "h": 11, "w": 5, "x": 9, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)\n",
       "legendFormat": "Available"
      },
      {
       "expr": "sum(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total"
      },
      {
       "expr": "predict_linear(\n  sum(\n    max by (compute_host) (\n      cortex_vmware_host_capacity_available{\n        resource=\"cpu\",\n        availability_zone=~\"$availability_zone\",\n        compute_host=~\"$compute_host\",\n        hypervisor_family=~\"$hypervisor_family\",\n        workload_type=\"hana\",\n        cpu_architecture=\"sapphire-rapids\",\n        pinned_projects=~\"(^$|.*$project_id.*)\",\n        enabled=\"true\"\n      }\n    )\n  )\n[56d:4h], 4838400)",
       "legendFormat": "Predicted Capacity"
      }
     ]
    },
    {
     "title": "RAM Capacity",
     "type": "stat",
     "gridPos": { "h": 11, "w": 5, "x": 14, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)\n",
       "legendFormat": "Available"
      },
      {
       "expr": "sum(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total"
      },
      {
       "expr": "predict_linear(\n  sum(\n    max by (compute_host) (\n      cortex_vmware_host_capacity_available{\n        resource=\"ram\",\n        availability_zone=~\"$availability_zone\",\n        compute_host=~\"$compute_host\",\n        hypervisor_family=~\"$hypervisor_family\",\n        workload_type=\"hana\",\n        cpu_architecture=\"sapphire-rapids\",\n        pinned_projects=~\"(^$|.*$project_id.*)\",\n        enabled=\"true\"\n      }\n    )\n  )\n[56d:4h], 4838400)",
       "legendFormat": "Predicted Capacity"
      }
     ]
    },
    {
     "title": "Disk Capacity",
     "type": "stat",
     "gridPos": { "h": 11, "w": 5, "x": 19, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "gbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)\n",
       "legendFormat": "Available"
      },
      {
       "expr": "sum(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=\"hana\",\n      cpu_architecture=\"sapphire-rapids\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=\"true\"\n    }\n  )\n)",
       "legendFormat": "Total"
      },
      {
       "expr": "predict_linear(\n  sum(\n    max by (compute_host) (\n      cortex_vmware_host_capacity_available{\n        resource=\"disk\",\n        availability_zone=~\"$availability_zone\",\n        compute_host=~\"$compute_host\",\n        hypervisor_family=~\"$hypervisor_family\",\n        workload_type=\"hana\",\n        cpu_architecture=\"sapphire-rapids\",\n        pinned_projects=~\"(^$|.*$project_id.*)\",\n        enabled=\"true\"\n      }\n    )\n  )\n[56d:4h], 4838400)",
       "legendFormat": "Predicted Capacity"
      }
     ]
    }
   ]
  },
  { "title": "Total Over Current Selection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "vCPU Capacity",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=~\"$workload_type\",\n      cpu_architecture=~\"$cpu_architecture\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=~\"$enabled\"\n    }\n  )\n)\n",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=~\"$workload_type\",\n      cpu_architecture=~\"$cpu_architecture\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=~\"$enabled\"\n    }\n  )\n)",
     "legendFormat": "Total"
    },
    {
     "expr": "predict_linear(\n  sum(\n    max by (compute_host) (\n      cortex_vmware_host_capacity_available{\n        resource=\"cpu\",\n        availability_zone=~\"$availability_zone\",\n        compute_host=~\"$compute_host\",\n        hypervisor_family=~\"$hypervisor_family\",\n        workload_type=~\"$workload_type\",\n        cpu_architecture=~\"$cpu_architecture\",\n        pinned_projects=~\"(^$|.*$project_id.*)\",\n        enabled=~\"$enabled\"\n      }\n    )\n  )\n[56d:4h], 4838400)",
     "legendFormat": "Predicted Capacity"
    }
   ]
  },
  {
   "title": "RAM Capacity",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=~\"$workload_type\",\n      cpu_architecture=~\"$cpu_architecture\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=~\"$enabled\"\n    }\n  )\n)\n",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=~\"$workload_type\",\n      cpu_architecture=~\"$cpu_architecture\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=~\"$enabled\"\n    }\n  )\n)",
     "legendFormat": "Total"
    },
    {
     "expr": "predict_linear(\n  sum(\n    max by (compute_host) (\n      cortex_vmware_host_capacity_available{\n        resource=\"ram\",\n        availability_zone=~\"$availability_zone\",\n        compute_host=~\"$compute_host\",\n        hypervisor_family=~\"$hypervisor_family\",\n        workload_type=~\"$workload_type\",\n        cpu_architecture=~\"$cpu_architecture\",\n        pinned_projects=~\"(^$|.*$project_id.*)\",\n        enabled=~\"$enabled\"\n      }\n    )\n  )\n[56d:4h], 4838400)",
     "legendFormat": "Predicted Capacity"
    }
   ]
  },
  {
   "title": "Disk Capacity",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  max by (compute_host, resource) (\n    cortex_vmware_host_capacity_available{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=~\"$workload_type\",\n      cpu_architecture=~\"$cpu_architecture\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=~\"$enabled\"\n    }\n  )\n)\n",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=~\"$workload_type\",\n      cpu_architecture=~\"$cpu_architecture\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=~\"$enabled\"\n    }\n  )\n)",
     "legendFormat": "Total"
    },
    {
     "expr": "predict_linear(\n  sum(\n    max by (compute_host) (\n      cortex_vmware_host_capacity_available{\n        resource=\"disk\",\n        availability_zone=~\"$availability_zone\",\n        compute_host=~\"$compute_host\",\n        hypervisor_family=~\"$hypervisor_family\",\n        workload_type=~\"$workload_type\",\n        cpu_architecture=~\"$cpu_architecture\",\n        pinned_projects=~\"(^$|.*$project_id.*)\",\n        enabled=~\"$enabled\"\n      }\n    )\n  )\n[56d:4h], 4838400)",
     "legendFormat": "Predicted Capacity"
    }
   ]
  },
  {
   "title": "vCPUs over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_available{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=~\"$workload_type\",\n      cpu_architecture=~\"$cpu_architecture\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=~\"$enabled\"\n    }\n  )\n)",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=~\"$workload_type\",\n      cpu_architecture=~\"$cpu_architecture\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=~\"$enabled\"\n    }\n  )\n)\n",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "RAM over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_available{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=~\"$workload_type\",\n      cpu_architecture=~\"$cpu_architecture\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=~\"$enabled\"\n    }\n  )\n)",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=~\"$workload_type\",\n      cpu_architecture=~\"$cpu_architecture\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=~\"$enabled\"\n    }\n  )\n)\n",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Disk over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_available{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=~\"$workload_type\",\n      cpu_architecture=~\"$cpu_architecture\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=~\"$enabled\"\n    }\n  )\n)",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_total{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=~\"$workload_type\",\n      cpu_architecture=~\"$cpu_architecture\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=~\"$enabled\"\n    }\n  )\n)\n",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Available vCPU Capacity per Host (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sort(\n  max by (compute_host, enabled) (\n    cortex_vmware_host_capacity_available_pct{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=~\"$workload_type\",\n      cpu_architecture=~\"$cpu_architecture\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=~\"$enabled\"\n    }\n  ) \n)",
     "legendFormat": "{{compute_host}} {{enabled}}"
    },
    {}
   ]
  },
  {
   "title": "Available RAM Capacity per Host (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sort(\n  max by (compute_host, enabled) (\n    cortex_vmware_host_capacity_available_pct{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=~\"$workload_type\",\n      cpu_architecture=~\"$cpu_architecture\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=~\"$enabled\"\n    }\n  ) \n)",
     "legendFormat": "{{compute_host}} {{enabled}}"
    }
   ]
  },
  {
   "title": "Available Disk Capacity per Host (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sort(\n  max by (compute_host, enabled) (\n    cortex_vmware_host_capacity_available_pct{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=~\"$workload_type\",\n      cpu_architecture=~\"$cpu_architecture\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=~\"$enabled\"\n    }\n  ) \n)",
     "legendFormat": "{{compute_host}} {{enabled}}"
    }
   ]
  },
  {
   "title": "Hosts",
   "type": "table",
   "gridPos": { "h": 28, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "# Add all column names here\nmax by (compute_host, enabled, disabled_reason, workload_type, availability_zone, cpu_architecture, pinned_projects) (cortex_vmware_host_capacity_available{resource=\"cpu\", availability_zone=~\"$availability_zone\", compute_host=~\"$compute_host\", hypervisor_family=~\"$hypervisor_family\", workload_type=~\"$workload_type\", enabled=~\"$enabled\", cpu_architecture=~\"$cpu_architecture\", pinned_projects=~\"(^$|.*$project_id.*)\"})"
    },
    {
     "expr": "max by (compute_host) (cortex_vmware_host_capacity_available{resource=\"ram\", availability_zone=~\"$availability_zone\", compute_host=~\"$compute_host\", hypervisor_family=~\"$hypervisor_family\", workload_type=~\"$workload_type\", enabled=~\"$enabled\", cpu_architecture=~\"$cpu_architecture\", pinned_projects=~\"(^$|.*$project_id.*)\"})"
    },
    {
     "expr": "max by (compute_host) (cortex_vmware_host_capacity_available{resource=\"disk\", availability_zone=~\"$availability_zone\", compute_host=~\"$compute_host\", hypervisor_family=~\"$hypervisor_family\", workload_type=~\"$workload_type\", enabled=~\"$enabled\", cpu_architecture=~\"$cpu_architecture\", pinned_projects=~\"(^$|.*$project_id.*)\"})"
    },
    {
     "expr": "max by (compute_host) (cortex_vmware_host_capacity_total{resource=\"cpu\", availability_zone=~\"$availability_zone\", compute_host=~\"$compute_host\", hypervisor_family=~\"$hypervisor_family\", workload_type=~\"$workload_type\", enabled=~\"$enabled\", cpu_architecture=~\"$cpu_architecture\", pinned_projects=~\"(^$|.*$project_id.*)\"})"
    },
    {
     "expr": "max by (compute_host) (cortex_vmware_host_capacity_total{resource=\"ram\", availability_zone=~\"$availability_zone\", compute_host=~\"$compute_host\", hypervisor_family=~\"$hypervisor_family\", workload_type=~\"$workload_type\", enabled=~\"$enabled\", cpu_architecture=~\"$cpu_architecture\", pinned_projects=~\"(^$|.*$project_id.*)\"})"
    },
    {
     "expr": "max by (compute_host) (cortex_vmware_host_capacity_total{resource=\"disk\", availability_zone=~\"$availability_zone\", compute_host=~\"$compute_host\", hypervisor_family=~\"$hypervisor_family\", workload_type=~\"$workload_type\", enabled=~\"$enabled\", cpu_architecture=~\"$cpu_architecture\", pinned_projects=~\"(^$|.*$project_id.*)\"})"
    },
    {
     "expr": "max by (compute_host) (cortex_sap_running_vms_per_host{availability_zone=~\"$availability_zone\", compute_host=~\"$compute_host\", hypervisor_family=~\"$hypervisor_family\", workload_type=~\"$workload_type\", enabled=~\"$enabled\", cpu_architecture=~\"$cpu_architecture\", pinned_projects=~\"(^$|.*$project_id.*)\"}) "
    }
   ]
  },
  {
   "title": "Available vCPU Capacity over Time (%)",
   "type": "heatmap",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "sort(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_available_pct{\n      resource=\"cpu\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=~\"$workload_type\",\n      cpu_architecture=~\"$cpu_architecture\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=~\"$enabled\"\n    }\n  ) \n)",
     "legendFormat": "{{compute_host}}"
    }
   ]
  },
  {
   "title": "Available RAM Capacity over Time (%)",
   "type": "heatmap",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "sort(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_available_pct{\n      resource=\"ram\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=~\"$workload_type\",\n      cpu_architecture=~\"$cpu_architecture\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=~\"$enabled\"\n    }\n  ) \n)",
     "legendFormat": "{{compute_host}}"
    }
   ]
  },
  {
   "title": "Available Disk Capacity over Time (%)",
   "type": "heatmap",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "sort(\n  max by (compute_host) (\n    cortex_vmware_host_capacity_available_pct{\n      resource=\"disk\",\n      availability_zone=~\"$availability_zone\",\n      compute_host=~\"$compute_host\",\n      hypervisor_family=~\"$hypervisor_family\",\n      workload_type=~\"$workload_type\",\n      cpu_architecture=~\"$cpu_architecture\",\n      pinned_projects=~\"(^$|.*$project_id.*)\",\n      enabled=~\"$enabled\"\n    }\n  ) \n)",
     "legendFormat": "{{compute_host}}"
    }
   ]
  },
  { "title": "Flavor Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127 } },
  {
   "title": "Running Workload",
   "type": "table",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 128 },
   "targets": [
    {
     "expr": "cortex_sap_flavor_running_vms{availability_zone=~\"$availability_zone\"}"
    }
   ]
  },
  {
   "title": "README",
   "type": "text",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 128 },
   "options": {
    "content": "# Flavor Usage\n\nThe table shows how many virtuals machines there are by flavor and availability zone. The only filter that you can apply here is the `availability_zone` filter.\n         "
   },
   "targets": [
    {}
   ]
  }
 ]
}