{
 "title": "Cortex KPIs",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "KPIs: NetApp Storage Pool CPU Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "NetApp Storage Pool CPU Usage (Maximum over 4 Weeks)",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(cortex_netapp_storage_pool_cpu_usage_max_bucket{}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "NetApp Storage Pool CPU Usage (Average over 4 Weeks)",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(cortex_netapp_storage_pool_cpu_usage_avg_bucket{}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "KPIs: VM Migrations and Time Until Migration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }
  },
  {
   "title": "Incoming migrations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by(target_host) (delta(cortex_migrations_total{}[2m])/2))",
     "legendFormat": "{{target_host}}"
    }
   ]
  },
  {
   "title": "Outgoing migrations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by(source_host) (delta(cortex_migrations_total{}[2m])/2))",
     "legendFormat": "{{target_host}}"
    }
   ]
  },
  {
   "title": "Residency of VMs migrated away (change over time)",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(delta(cortex_vm_time_until_migration_bucket{flavor_name=\"all\"}[2m]) / 2) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Residency of VMs migrated away (total)",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum(cortex_vm_time_until_migration_bucket{flavor_name=\"all\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Migrations by flavor",
   "type": "stat",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(sum by (flavor_name) (cortex_vm_time_until_migration_count))",
     "legendFormat": "{{flavor_name}}"
    }
   ]
  },
  {
   "title": "Average time until migration by flavor",
   "type": "stat",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(sum by (flavor_name) (cortex_vm_time_until_migration_sum) / sum by (flavor_name) (cortex_vm_time_until_migration_count))",
     "legendFormat": "{{flavor_name}}"
    }
   ]
  },
  {
   "title": "Migrations by type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(type) (delta(cortex_migrations_total[2m])/2)",
     "legendFormat": "{{target_host}}"
    }
   ]
  },
  { "title": "KPIs: VM Life Span", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Life span of deleted VMs (change over time)",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "sum(delta(cortex_vm_life_span_bucket{flavor_name=\"all\"}[2m]) / 2) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Life span of deleted VMs (total)",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "sum(cortex_vm_life_span_bucket{flavor_name=\"all\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Newly created vms by flavor",
   "type": "stat",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(sum by (flavor_name) (cortex_vm_life_span_count))",
     "legendFormat": "{{flavor_name}}"
    }
   ]
  },
  {
   "title": "Average life span of newly created vms by flavor",
   "type": "stat",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(sum by (flavor_name) (cortex_vm_life_span_sum) / sum by (flavor_name) (cortex_vm_life_span_count))",
     "legendFormat": "{{flavor_name}}"
    }
   ]
  },
  {
   "title": "KPIs: Hypervisor Resource Available Capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 }
  },
  {
   "title": "Hypervisor Resources Available Capacity (CPU %)",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "sum(cortex_sap_available_capacity_pct_bucket{resource=\"cpu\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Hypervisor Resources Available Capacity (RAM %)",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 80 },
   "targets": [
    {
     "expr": "sum(cortex_sap_available_capacity_pct_bucket{resource=\"ram\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Hypervisor Resources Available Capacity (Disk %)",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 92 },
   "targets": [
    {
     "expr": "sum(cortex_sap_available_capacity_pct_bucket{resource=\"disk\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Top 20 Utilization (CPU %)",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 4, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(topk(20, 100-cortex_sap_available_capacity_per_host_pct{resource=\"cpu\"}))",
     "legendFormat": "{{compute_host}}"
    }
   ]
  },
  {
   "title": "Top 20 Utilization (Reserved, Memory %)",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 4, "x": 16, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(topk(20,100-cortex_sap_available_capacity_per_host_pct{resource=\"ram\"}))",
     "legendFormat": "{{compute_host}}"
    }
   ]
  },
  {
   "title": "Top 20 Utilization (Reserved, Disk %)",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 4, "x": 20, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(topk(20,100-cortex_sap_available_capacity_per_host_pct{resource=\"disk\"}))",
     "legendFormat": "{{compute_host}}"
    }
   ]
  },
  {
   "title": "KPIs: VMware Host CPU Contention",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 }
  },
  {
   "title": "VMware Host CPU Contention (Maximum over 4 Weeks)",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 105 },
   "targets": [
    {
     "expr": "sum(cortex_vmware_host_cpu_contention_max_bucket{}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "VMware Host CPU Contention (Average over 4 Weeks)",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 105 },
   "targets": [
    {
     "expr": "sum(cortex_vmware_host_cpu_contention_avg_bucket{}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "KPIs: VMware Project Noisiness", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 } },
  {
   "title": "VMware Project Noisiness on Host (Avg. CPU % over 4 Weeks)",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 118 },
   "targets": [
    {
     "expr": "sum(cortex_vmware_project_noisiness_bucket{}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}