{
 "title": "Cortex Reservations",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Readme", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Readme",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "# Readme\n\nReservations are generated from limes commitments that are for a concrete flavor (so called instance commitments). Commitments for bare resources are not processed by cortex as there is no way to tell where and how many vms would be placed. "
   },
   "targets": [
    {}
   ]
  },
  { "title": "Reservations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "vCPUs Reserved",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "vCPUs" } },
   "targets": [
    {
     "expr": "max by (host) (cortex_reservations_resources{status_phase=\"active\",resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "vCPUs Reserved",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "max by (host) (cortex_reservations_resources{status_phase=\"active\",resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Total Resources Reserved",
   "type": "stat",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (resource) (cortex_reservations_resources{status_phase=\"active\"})",
     "legendFormat": "{{ resource }}"
    }
   ]
  },
  {
   "title": "vCPUs Not Reservable",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "vCPUs" } },
   "targets": [
    {
     "expr": "max by (status_error) (cortex_reservations_resources{status_phase!=\"active\",resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "vCPUs Not Reservable",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "max by (status_error) (cortex_reservations_resources{status_phase!=\"active\",resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Total Resources Not Reservable",
   "type": "stat",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (resource) (cortex_reservations_resources{status_phase!=\"active\"})",
     "legendFormat": "{{ resource }}"
    }
   ]
  },
  { "title": "Operator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Time to reconcile",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(controller_runtime_reconcile_time_seconds_bucket{controller=\"reservation\"}[2m])) by (le))",
     "legendFormat": "Compute reservations controller"
    }
   ]
  },
  {
   "title": "Reconcile issues rate",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(controller_runtime_reconcile_errors_total{controller=\"reservation\"}[2m])",
     "legendFormat": "Errors compute reservations controller"
    },
    {
     "expr": "rate(controller_runtime_reconcile_panics_total{controller=\"reservation\"}[2m])",
     "legendFormat": "Panics compute reservations controller"
    }
   ]
  }
 ]
}