{
 "title": "Cortex Database",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Database Size",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "pg_database_size_bytes{pod=~\"cortex-.*-postgresql-0\",datname=\"postgres\"}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Table Size",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "increase(pg_stat_user_tables_size_bytes{pod=~\"cortex-.*-postgresql-0\",datname=\"postgres\"}[2m])",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Time Spent Executing SQL",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_active_time_seconds_total{pod=~\"cortex-.*-postgresql-0\",datname=\"postgres\"}[2m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(pg_stat_database_tup_fetched{pod=~\"cortex-.*-postgresql-0\",datname=\"postgres\"}[2m])",
     "legendFormat": "Rows Fetched"
    },
    {
     "expr": "increase(pg_stat_database_tup_inserted{pod=~\"cortex-.*-postgresql-0\",datname=\"postgres\"}[2m])",
     "legendFormat": "Rows Inserted"
    },
    {
     "expr": "increase(pg_stat_database_tup_deleted{pod=~\"cortex-.*-postgresql-0\",datname=\"postgres\"}[2m])",
     "legendFormat": "Rows Deleted"
    }
   ]
  },
  {
   "title": "Index Scans",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(pg_stat_user_tables_idx_scan{pod=~\"cortex-.*-postgresql-0\",datname=\"postgres\"}[2m])",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Sequential Scans",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(pg_stat_user_tables_seq_scan{pod=~\"cortex-.*-postgresql-0\",datname=\"postgres\"}[2m])",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Rows Deleted by Table",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(pg_stat_user_tables_n_tup_del{pod=~\"cortex-.*-postgresql-0\",datname=\"postgres\"}[2m])",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Rows Read by Table",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(pg_stat_user_tables_seq_tup_read{pod=~\"cortex-.*-postgresql-0\",datname=\"postgres\"}[2m])",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Rows Updated by Table",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(pg_stat_user_tables_n_tup_upd{pod=~\"cortex-.*-postgresql-0\",datname=\"postgres\"}[2m])",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Rows Inserted by Table",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(pg_stat_user_tables_n_tup_ins{pod=~\"cortex-.*-postgresql-0\",datname=\"postgres\"}[2m])",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Live Rows / Total Rows",
   "type": "stat",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_user_tables_n_live_tup{pod=~\"cortex-.*-postgresql-0\",datname=\"postgres\"} / (pg_stat_user_tables_n_dead_tup{pod=~\"cortex-.*-postgresql-0\",datname=\"postgres\"} + pg_stat_user_tables_n_live_tup{pod=~\"cortex-.*-postgresql-0\",datname=\"postgres\"})",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  { "title": "Database Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Connections Open",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (go_sql_stats_connections_open{github_org=\"cobaltcore-dev\",github_repo=\"cortex\"})",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Connections In Use",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (go_sql_stats_connections_in_use{github_org=\"cobaltcore-dev\",github_repo=\"cortex\"})",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Connections Idle",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (go_sql_stats_connections_idle{github_org=\"cobaltcore-dev\",github_repo=\"cortex\"})",
     "legendFormat": "{{ container }}"
    }
   ]
  }
 ]
}