{
 "title": "Cortex Status Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Custom Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Datasource status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(datasource) (cortex_datasource_state{state!=\"ready\"}) * 0",
     "legendFormat": "{{datasource}}"
    },
    {
     "expr": "max by(datasource) (cortex_datasource_state{state=\"ready\"}) * 1",
     "legendFormat": "{{datasource}}"
    }
   ]
  },
  {
   "title": "Knowledge status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(knowledge) (cortex_knowledge_state{state!=\"ready\"}) * 0",
     "legendFormat": "{{knowledge}}"
    },
    {
     "expr": "max by(knowledge) (cortex_knowledge_state{state=\"ready\"}) * 1",
     "legendFormat": "{{knowledge}}"
    }
   ]
  },
  {
   "title": "Pipeline status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(pipeline) (cortex_pipeline_state{state!=\"ready\"}) * 0",
     "legendFormat": "{{pipeline}}"
    },
    {
     "expr": "max by(pipeline) (cortex_pipeline_state{state=\"ready\"}) * 1",
     "legendFormat": "{{pipeline}}"
    }
   ]
  },
  {
   "title": "KPI status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(kpi) (cortex_kpi_state{state!=\"ready\"}) * 0",
     "legendFormat": "{{kpi}}"
    },
    {
     "expr": "max by(kpi) (cortex_kpi_state{state=\"ready\"}) * 1",
     "legendFormat": "{{kpi}}"
    }
   ]
  },
  { "title": "Scheduling Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Pipeline: kvm-* (Nova)",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pipeline: manila-external-scheduler",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Nova: from which idx the selected host came from",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(delta(cortex_filter_weigher_pipeline_step_shift_origin_bucket{outidx=\"0\",pipeline=~\"kvm-.*\"}[2m]) / 2) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Manila: from which idx the selected host came from",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum(delta(cortex_filter_weigher_pipeline_step_shift_origin_bucket{outidx=\"0\",pipeline=\"manila-external-scheduler\"}[2m]) / 2) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Nova: faults in vm scheduling lifecycle",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (faultmsg,state) (cortex_vm_faults{faultcode!=\"0\"})",
     "legendFormat": "{{state}} {{faultmsg}}"
    }
   ]
  },
  {
   "title": "Weight modifications",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pipeline, host, step, alias) (delta(cortex_filter_weigher_pipeline_step_weight_modification[2m]))",
     "legendFormat": "{{ pipeline }} {{ host }} {{ step }} ({{ alias }})"
    }
   ]
  },
  {
   "title": "Successful request rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cortex_scheduler_api_request_duration_seconds_count{status=~\"2.+\"}[2m])) by (method, path, status, error)",
     "legendFormat": "{{method}} {{path}} {{status}} {{error}}"
    }
   ]
  },
  {
   "title": "Error request rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cortex_scheduler_api_request_duration_seconds_count{status=~\"4.+|5.+\"}[2m])) by (method, path, status, error)",
     "legendFormat": "{{method}} {{path}} {{status}} {{error}}"
    }
   ]
  },
  {
   "title": "Average response time (success)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_scheduler_api_request_duration_seconds_bucket{status=~\"2.+\"}[2m])) by (le, method, path, status, error))",
     "legendFormat": "{{method}} {{path}} {{status}} {{error}}"
    }
   ]
  },
  {
   "title": "Average response time (error)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_scheduler_api_request_duration_seconds_bucket{status=~\"4.+|5.+\"}[2m])) by (le, method, path, status, error))",
     "legendFormat": "{{method}} {{path}} {{status}} {{error}}"
    }
   ]
  },
  {
   "title": "Time needed to run scheduler steps",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_filter_weigher_pipeline_step_run_duration_seconds_bucket[2m])) by (le, step, alias, pipeline))",
     "legendFormat": "{{pipeline}} {{step}}"
    }
   ]
  },
  {
   "title": "Requests by type (rate over 2min)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by(pipeline) (rate(cortex_filter_weigher_pipeline_requests_total{}[2m]))",
     "legendFormat": "Pipeline: {{pipeline}}"
    }
   ]
  },
  { "title": "Kubernetes Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{pod=~\"cortex-.*\"} / 1_000_000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{pod=~\"cortex-.*\"}[2m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "All Pods Up?",
   "type": "stat",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{pod=~\"cortex-.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Datasources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 } },
  {
   "title": "New objects synced",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by(datasource) (increase(cortex_sync_objects[2m]))",
     "legendFormat": "{{ datasource }}"
    }
   ]
  },
  {
   "title": "Times synced",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by(datasource) (increase(cortex_sync_request_processed_total[2m]))",
     "legendFormat": "{{ datasource }}"
    }
   ]
  },
  { "title": "Descheduling Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 } },
  {
   "title": "Time needed to deschedule VM",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_descheduler_pipeline_vm_descheduling_duration_seconds_bucket[2m])) by (le, error, skipped))",
     "legendFormat": "Error: {{error}}, Skipped: {{skipped}}"
    }
   ]
  },
  {
   "title": "Deschedulings (rate over 2min)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 118 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by(error) (rate(cortex_detector_pipeline_run_duration_seconds_count{}[2m]))",
     "legendFormat": "Error: {{error}}"
    }
   ]
  },
  {
   "title": "Time needed to run descheduler steps",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 131 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_detector_pipeline_step_run_duration_seconds_bucket[2m])) by (le, step))",
     "legendFormat": "{{step}}"
    }
   ]
  },
  {
   "title": "Triggered migrations",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 131 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (error) (delta(cortex_detector_pipeline_run_duration_seconds_count{}[2m]))",
     "legendFormat": "Error: {{error}}"
    }
   ]
  }
 ]
}