{
 "title": "Cortex Placement Shim Status",
 "description": "Cortex Placement Shim status dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Downstream Requests (Client → Shim)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Downstream successful request rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cortex_placement_shim_downstream_request_duration_seconds_count{responsecode=~\"2..\"}[2m])) by (method, pattern, responsecode)",
     "legendFormat": "{{method}} {{pattern}} {{responsecode}}"
    }
   ]
  },
  {
   "title": "Downstream error request rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cortex_placement_shim_downstream_request_duration_seconds_count{responsecode=~\"4..|5..\"}[2m])) by (method, pattern, responsecode)",
     "legendFormat": "{{method}} {{pattern}} {{responsecode}}"
    }
   ]
  },
  {
   "title": "Downstream p95 latency (successful)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_placement_shim_downstream_request_duration_seconds_bucket{responsecode=~\"2..\"}[2m])) by (le, method, pattern))",
     "legendFormat": "{{method}} {{pattern}}"
    }
   ]
  },
  {
   "title": "Downstream p95 latency (errors)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_placement_shim_downstream_request_duration_seconds_bucket{responsecode=~\"4..|5..\"}[2m])) by (le, method, pattern))",
     "legendFormat": "{{method}} {{pattern}}"
    }
   ]
  },
  {
   "title": "Upstream Requests (Shim → Placement API)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }
  },
  {
   "title": "Upstream successful request rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cortex_placement_shim_upstream_request_duration_seconds_count{responsecode=~\"2..\"}[2m])) by (method, pattern, responsecode)",
     "legendFormat": "{{method}} {{pattern}} {{responsecode}}"
    }
   ]
  },
  {
   "title": "Upstream error request rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cortex_placement_shim_upstream_request_duration_seconds_count{responsecode=~\"4..|5..\"}[2m])) by (method, pattern, responsecode)",
     "legendFormat": "{{method}} {{pattern}} {{responsecode}}"
    }
   ]
  },
  {
   "title": "Upstream p95 latency (successful)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_placement_shim_upstream_request_duration_seconds_bucket{responsecode=~\"2..\"}[2m])) by (le, method, pattern))",
     "legendFormat": "{{method}} {{pattern}}"
    }
   ]
  },
  {
   "title": "Upstream p95 latency (errors)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_placement_shim_upstream_request_duration_seconds_bucket{responsecode=~\"4..|5..\"}[2m])) by (le, method, pattern))",
     "legendFormat": "{{method}} {{pattern}}"
    }
   ]
  },
  { "title": "Kubernetes Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Memory usage (MiB)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{pod=~\"cortex-placement-shim-.*\"} / 1_000_000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU usage (cores)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{pod=~\"cortex-placement-shim-.*\"}[2m])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}