# This rule is not used by the project decisions itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the decisions.cortex.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: decisions
    app.kubernetes.io/managed-by: kustomize
  name: schedulingdecision-editor-role
rules:
- apiGroups:
  - decisions.cortex
  resources:
  - schedulingdecisions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - decisions.cortex
  resources:
  - schedulingdecisions/status
  verbs:
  - get
