---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - decisions.cortex
  resources:
  - computedecisions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - decisions.cortex
  resources:
  - computedecisions/finalizers
  verbs:
  - update
- apiGroups:
  - decisions.cortex
  resources:
  - computedecisions/status
  verbs:
  - get
  - patch
  - update
