---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - decisions.cortex
  resources:
  - schedulingdecisions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - decisions.cortex
  resources:
  - schedulingdecisions/finalizers
  verbs:
  - update
- apiGroups:
  - decisions.cortex
  resources:
  - schedulingdecisions/status
  verbs:
  - get
  - patch
  - update
