{{- if .Values.rbac.enable }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: {{ .Values.namePrefix }}-manager-role
rules:
- apiGroups:
  - cortex.cloud
  resources:
  - knowledges
  - datasources
  - reservations
  - committedresources
  - projectquotas
  - flavorgroupcapacities
  - decisions
  - deschedulings
  - pipelines
  - kpis
  - histories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cortex.cloud
  resources:
  - knowledges/finalizers
  - datasources/finalizers
  - reservations/finalizers
  - committedresources/finalizers
  - projectquotas/finalizers
  - flavorgroupcapacities/finalizers
  - decisions/finalizers
  - deschedulings/finalizers
  - pipelines/finalizers
  - kpis/finalizers
  - histories/finalizers
  verbs:
  - update
- apiGroups:
  - cortex.cloud
  resources:
  - knowledges/status
  - datasources/status
  - reservations/status
  - committedresources/status
  - projectquotas/status
  - flavorgroupcapacities/status
  - decisions/status
  - deschedulings/status
  - pipelines/status
  - kpis/status
  - histories/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
{{- end -}}
