# This rule is not used by the project reservations itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to reservations.cortex resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: reservations
    app.kubernetes.io/managed-by: kustomize
  name: reservation-viewer-role
rules:
- apiGroups:
  - reservations.cortex
  resources:
  - reservations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - reservations.cortex
  resources:
  - reservations/status
  verbs:
  - get
