---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - reservations.cortex
  resources:
  - computereservations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - reservations.cortex
  resources:
  - computereservations/finalizers
  verbs:
  - update
- apiGroups:
  - reservations.cortex
  resources:
  - computereservations/status
  verbs:
  - get
  - patch
  - update
