apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cortex-alerts
  labels:
    tier: os
    type: alerting-rules
    prometheus: {{ .Values.global.prometheus }}
spec:
  groups:
  - name: cortex-alerts
    rules:
    - alert: CortexDown
      expr: up{github_org="cobaltcore-dev",github_repo="cortex"} == 0
      for: 1m
      labels:
        severity: warning
        context: liveness
        {{- with .Values.alerts.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.alerts.cortexDown.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.alerts.warning.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        summary: "Cortex service is down"
        description: "The service is not responding."

    - alert: CortexHttpRequest400sTooHigh
      expr: rate(cortex_scheduler_api_request_duration_seconds_count{status=~"4.+"}[5m]) > 0
      for: 5m
      labels:
        severity: info
        context: api
        {{- with .Values.alerts.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.alerts.cortexHttpRequest400sTooHigh.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.alerts.info.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        summary: "HTTP request 400 errors too high"
        description: "The rate of HTTP request 400 errors is too high."

    - alert: CortexHttpRequest500sTooHigh
      expr: rate(cortex_scheduler_api_request_duration_seconds_count{status=~"5.+"}[5m]) > 0
      for: 5m
      labels:
        severity: warning
        context: api
        {{- with .Values.alerts.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.alerts.cortexHttpRequest500sTooHigh.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.alerts.warning.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        summary: "HTTP request 500 errors too high"
        description: "The rate of HTTP request 500 errors is too high."

    - alert: CortexHighMemoryUsage
      expr: process_resident_memory_bytes{github_org="cobaltcore-dev",github_repo="cortex"} > 100 * 1024 * 1024
      for: 5m
      labels:
        severity: info
        context: memory
        {{- with .Values.alerts.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.alerts.cortexHighMemoryUsage.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.alerts.info.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        summary: "High memory usage"
        description: "The service is using more than 100 MiB of memory."

    - alert: CortexHighCPUUsage
      expr: rate(process_cpu_seconds_total{github_org="cobaltcore-dev",github_repo="cortex"}[1m]) > 0.5
      for: 5m
      labels:
        severity: info
        context: cpu
        {{- with .Values.alerts.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.alerts.cortexHighCPUUsage.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.alerts.info.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        summary: "High CPU usage"
        description: "The service is using more than 50% CPU."

    - alert: CortexLongPipelineRun
      expr: histogram_quantile(0.99, rate(cortex_pipeline_run_duration_seconds_bucket[5m])) > 1
      for: 5m
      labels:
        severity: info
        context: pipeline
        {{- with .Values.alerts.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.alerts.cortexLongPipelineRun.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.alerts.info.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        summary: "Pipeline run duration too long"
        description: "The pipeline takes more than 1 second to run."

    - alert: CortexSyncNotSuccessful
      expr: cortex_sync_request_processed_total - cortex_sync_request_duration_seconds_count > 0
      for: 5m
      labels:
        severity: info
        context: syncstatus
        {{- with .Values.alerts.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.alerts.cortexSyncNotSuccessful.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.alerts.info.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        summary: "Sync not successful"
        description: "There are sync requests that are not successful."

    - alert: CortexSyncObjectsDroppedToZero
      expr: cortex_sync_objects_total == 0
      for: 5m
      labels:
        severity: info
        context: syncobjects
        {{- with .Values.alerts.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.alerts.cortexSyncObjectsDroppedToZero.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.alerts.info.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        summary: "Sync objects dropped to zero"
        description: "The number of sync objects has dropped to zero for some resource."