apiVersion: v2
name: cortex-shim
description: A Helm chart to distribute cortex shims.
type: application
version: 0.1.19
appVersion: "sha-3bc1856b"
icon: "https://example.com/icon.png"
dependencies: []
