---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - compute.ironcore.dev
  resources:
  - machineclasses
  - machinepools
  - machines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compute.ironcore.dev
  resources:
  - machineclasses/finalizers
  - machinepools/finalizers
  - machines/finalizers
  verbs:
  - update
- apiGroups:
  - compute.ironcore.dev
  resources:
  - machineclasses/status
  - machinepools/status
  - machines/status
  verbs:
  - get
  - patch
  - update
