apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: features.extractor.cortex.sap
spec:
  group: extractor.cortex.sap
  names:
    kind: Feature
    listKind: FeatureList
    plural: features
    singular: feature
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: Feature is the Schema for the features API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: FeatureSpec defines the desired state of Feature.
            properties:
              foo:
                description: Foo is an example field of Feature. Edit feature_types.go
                  to remove/update
                type: string
            type: object
          status:
            description: FeatureStatus defines the observed state of Feature.
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cortex-feature-manager-role
rules:
- apiGroups:
  - extractor.cortex.sap
  resources:
  - features
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extractor.cortex.sap
  resources:
  - features/finalizers
  verbs:
  - update
- apiGroups:
  - extractor.cortex.sap
  resources:
  - features/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - extractor.cortex.sap
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cortex-feature-manager-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cortex-feature-manager-role
subjects:
- kind: ServiceAccount
  name: cortex-feature-manager
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cortex-feature-manager
