apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cortex-scheduling-quality-exporter.fullname" . }}
  labels:
    {{- include "cortex-scheduling-quality-exporter.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - openstack.sapcloud.io
    resources:
      - hypervisors
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cortex-scheduling-quality-exporter.fullname" . }}
  labels:
    {{- include "cortex-scheduling-quality-exporter.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cortex-scheduling-quality-exporter.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "cortex-scheduling-quality-exporter.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
