{{- if include "cortex-scheduling-quality-exporter.novaEnabled" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cortex-scheduling-quality-exporter.osSecretName" . }}
  labels:
    {{- include "cortex-scheduling-quality-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  OS_AUTH_URL: {{ .Values.openstack.authURL | quote }}
  OS_USERNAME: {{ .Values.openstack.username | quote }}
  OS_PASSWORD: {{ .Values.openstack.password | quote }}
  OS_PROJECT_NAME: {{ .Values.openstack.projectName | quote }}
  OS_USER_DOMAIN_NAME: {{ .Values.openstack.userDomainName | quote }}
  OS_PROJECT_DOMAIN_NAME: {{ .Values.openstack.projectDomainName | quote }}
{{- end }}
