# Copyright 2025 SAP SE
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cortex-visualizer
  labels:
    app: cortex-visualizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cortex-visualizer
  template:
    metadata:
      labels:
        app: cortex-visualizer
    spec:
      containers:
        - name: cortex-visualizer # from local tilt build
          image: cortex-visualizer
          ports:
            - containerPort: 3000