# Copyright 2025 SAP SE
# SPDX-License-Identifier: Apache-2.0

FROM nginx
COPY vendor/mqtt.min.js /usr/share/nginx/html/mqtt.min.js
COPY nova.html /usr/share/nginx/html/nova.html
COPY shared.css /usr/share/nginx/html/shared.css
COPY favicon.ico /usr/share/nginx/html/favicon.ico
