{{- if .Values.kvm.enabled }}
---
apiVersion: cortex.cloud/v1alpha1
kind: Knowledge
metadata:
  name: flavor-groups
spec:
  schedulingDomain: nova
  extractor:
    name: flavor_groups
  recency: "5m"
  description: |
    This knowledge extracts flavor groups from Nova flavors based on the
    hw_version extra_spec. It identifies all flavors belonging to each group
    and determines the largest flavor for reservation slot sizing.
  dependencies:
    datasources:
      - name: nova-flavors
---
apiVersion: cortex.cloud/v1alpha1
kind: Knowledge
metadata:
  name: kvm-libvirt-domain-cpu-steal-pct
spec:
  schedulingDomain: nova
  recency: "60s"
  extractor:
    name: kvm_libvirt_domain_cpu_steal_pct_extractor
  description: |
    This knowledge identifies KVM libvirt domains that are experiencing CPU
    steal, i.e. cpu contention or cpu wait.
  dependencies:
    datasources:
      - name: kvm-libvirt-domain-steal-pct
      - name: nova-servers
{{- end }}