{{- $namePrefix := (index .Values "cortex-scheduling-controllers").namePrefix -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $namePrefix }}-webhook-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    app.kubernetes.io/name: cortex-scheduling-controllers
    app.kubernetes.io/instance: {{ .Release.Name }}
    control-plane: controller-manager
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $namePrefix }}-webhook-cert
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
    - {{ $namePrefix }}-webhook-service.{{ .Release.Namespace }}.svc
    - {{ $namePrefix }}-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ $namePrefix }}-selfsigned-issuer
  secretName: {{ $namePrefix }}-webhook-server-cert
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ $namePrefix }}-validating-webhook-configuration
  annotations:
    "cert-manager.io/inject-ca-from": {{ .Release.Namespace }}/{{ $namePrefix }}-webhook-cert
webhooks:
  - name: {{ $namePrefix }}-validate-v1alpha1-pipeline.cortex.cloud
    admissionReviewVersions: [v1]
    clientConfig:
      service:
        name: {{ $namePrefix }}-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-cortex-cloud-v1alpha1-pipeline
    timeoutSeconds: 10
    failurePolicy: Ignore
    rules:
      - apiGroups:
          - cortex.cloud
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pipelines
    sideEffects: None
