# Copyright 2025 SAP SE
# SPDX-License-Identifier: Apache-2.0

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cortex-core-services
  labels:
    name: cortex-core-services
    prometheus: openstack
    app: cortex
spec:
  selector:
    matchLabels:
      # Select all services from the Cortex helm chart.
      app.kubernetes.io/name: cortex
  namespaceSelector:
    any: true
  targetLabels:
    - component
  endpoints:
    - port: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cortex-postgres
  labels:
    name: cortex-postgres
    prometheus: openstack
    app: cortex
spec:
  selector:
    matchLabels:
      # Select the postgres service.
      app.kubernetes.io/instance: cortex-postgres
  namespaceSelector:
    any: true
  endpoints:
    - port: http-metrics
