name: Lint
"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch: {}
permissions:
  checks: write
  contents: read
jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - name: Run golangci-lint
        run: |
          set -eux
          make lint
