name: Update Helm Image Tag

on:
  workflow_run:
    workflows: ["Docker Build and Push"] # Replace with the actual workflow name that builds & pushes the Docker image
    types:
      - completed

jobs:
  update-helm-tag:
    if: >-
      ${{ github.event.workflow_run.conclusion == 'success' && !contains(github.event.workflow_run.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Get short commit SHA
        id: vars
        run: echo "sha=sha-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Update image.tag in values.yaml
        run: |
          sed -i 's/^\([ ]*tag:[ ]*\).*/\1"${{ steps.vars.outputs.sha }}"/' helm/cortex/values.yaml

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add helm/cortex/values.yaml
          git commit -m "Bump cortex image tag in chart to ${{ steps.vars.outputs.sha }} [skip ci]" || echo "No changes to commit"
          git push
