# Copyright 2025 SAP SE
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: cortex
description: A Helm chart for deploying Cortex.
type: application
version: 0.17.0
appVersion: 0.1.0
dependencies:
  # Owner info adds a configmap to the kubernetes cluster with information on
  # the service owner. This makes it easier to find out who to contact in case
  # of issues. See: https://github.com/sapcc/helm-charts/pkgs/container/helm-charts%2Fowner-info
  - name: owner-info
    repository: oci://ghcr.io/sapcc/helm-charts
    version: 1.0.0
