# All secrets should be put under this key.
# These values will not be included in the config.json file.
# TODO: Include these in the config.json file if that's not a security risk.
secrets:
  postgres:
    port: "5432"
    database: postgres
    username: postgres
    password: secret
    host: cortex-postgresql

  openstack:
    # Replace with your OpenStack credentials, e.g. by secret injection.
    authUrl: https://path-to-keystone/v3
    username: openstack-user-with-all-project-read-access
    password: openstack-user-password
    projectName: openstack-project-of-user
    userDomainName: openstack-domain-of-user
    projectDomainName: openstack-domain-of-project-scoped-to

  prometheus:
    url: https://path-to-prometheus
    # Optional, only required if Prometheus is configured with SSO.
    ssoPublicKey:
    ssoPrivateKey:

image:
  repository: cortex
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "main"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

modes:
  - name: syncer
    service:
      type: ClusterIP
      metricsPort: 2112
    args: ["--syncer"]
    replicas: 1
  - name: extractor
    service:
      type: ClusterIP
      metricsPort: 2112
    args: ["--extractor"]
    replicas: 1
  - name: scheduler
    service:
      type: ClusterIP
      apiPort: 8080
      metricsPort: 2112
    args: ["--scheduler"]
    replicas: 2

resources:
  limits:
    cpu: 250m
    memory: 1024Mi

livenessProbe:
  httpGet:
    path: /metrics
    port: metrics
readinessProbe:
  httpGet:
    path: /metrics
    port: metrics

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}

owner-info:
  helm-chart-url: "https://github.tools.sap/cobaltcore-dev/cortex/helm/cortex"
  maintainers:
    - "p.matthes@sap.com"
  support-group: "cobaltcore-dev"
  enabled: true

# ######### Values passed to the service by conf.yaml ###########
conf:
  monitoring:
    # Custom labels added to the exported metrics.
    labels:
      github_org: cobaltcore-dev
      github_repo: cortex
  sync:
    prometheus:
      metrics:
        - name: vrops_virtualmachine_cpu_demand_ratio
          type: vrops_vm_metric
        - name: vrops_hostsystem_cpu_contention_percentage
          type: vrops_host_metric
    openstack:
      hypervisors: true
      servers: true
  features:
    extractors:
      - name: vrops_hostsystem_resolver
        dependencies:
          sync:
            prometheus:
              metrics:
                # Any vrops vm metric suffices.
                - vrops_virtualmachine_cpu_demand_ratio
            openstack:
              hypervisors: true
              servers: true
      - name: vrops_project_noisiness_extractor
        dependencies:
          sync:
            prometheus:
              metrics:
                - vrops_virtualmachine_cpu_demand_ratio
            openstack:
              hypervisors: true
              servers: true
      - name: vrops_hostsystem_contention_extractor
        dependencies:
          features:
            extractors:
              - vrops_hostsystem_resolver
          sync:
            prometheus:
              metrics:
                - vrops_hostsystem_cpu_contention_percentage
  scheduler:
    logRequestBodies: true # debugging feature
    steps:
      - name: vrops_anti_affinity_noisy_projects
        options:
          avgCPUThreshold: 20
          activationOnHit: -1.0
        dependencies:
          features:
            extractors:
              - vrops_project_noisiness_extractor
      - name: vrops_avoid_contended_hosts
        options:
          avgCPUContentionThreshold: 10
          maxCPUContentionThreshold: 20
          activationOnHit: -1.0
        dependencies:
          features:
            extractors:
              - vrops_hostsystem_contention_extractor
